### ISSUE TITLE
(Enhancement) Add a Toggle to Hide Users in Hidden Voice Channels

### ISSUE THREAD

**Issue by Ryonez** [JustOptimize/return-ShowHiddenChannels#101]
Currently, users in a hidden voice channel are displayed with no option to not display them.
Users might not want to see folks in channels they can't join, or see streaming icons for server when again they can't join.

**Comment by JustOptimize** [comment]
> Users might not want to see folks in channels they can't join, or see streaming icons for server when again they can't join.

This is nonsence btw, discord already does this with voice channels you see but can't join

**Comment by Ryonez** [comment]
Doesn't mean it's nonsense, means they'll have to put up with it there to. Personally haven't noticed that myself as I don't know of any channels like that. I do see it in hidden channels though.

**Comment by JustOptimize** [comment]
> @Ryonez whats the point of this enhancement, its better if you can just simply bypass it or join the hidden voice channel

Wym, you can't bypass it/join the hidden voice channel....
He wants to see the channels but not if users are connected

**Comment by Ryonez** [comment]
Well, heck.
