### ISSUE TITLE
(Enhancement) View Voice Channel Permissions

### ISSUE THREAD

**Issue by Ryonez** [JustOptimize/return-ShowHiddenChannels#102]
Allow seeing the permissions a voice channel has on it.

**Comment by samzillaa** [comment]
Ya hope you can add that back and thank you for brining that plugin back.

**Comment by Ryonez** [comment]
That is a good stand in, thanks.

**Comment by JustOptimize** [comment]
Added this feature in the dev branch 867ccdcc864c86a86c90cc1be56127ff583eefa3, after some testing it will be merged in the main and be avaiable to everyone.

If you want to test this you can download the dev version [here](https://raw.githubusercontent.com/JustOptimize/return-ShowHiddenChannels/dev-unstable/ShowHiddenChannels.plugin.js)
