### ISSUE TITLE
[CRASH] Crash after install

### ISSUE THREAD

**Issue by BySwiizen** [JustOptimize/return-ShowHiddenChannels#103]
Hi, I just installed the plugin and it keeps crashing even after restarting. A solution ?
![DiscordCanary_VFpbDczFSN](https://user-images.githubusercontent.com/29678500/221696791-49449384-72b8-4af8-9fb3-44e22463a654.png)

**Comment by syth911** [comment]
I can confirm. After today's update this plugin crashes Discord. Please fix :)

**Comment by sacapatata** [comment]
yep, same  problem for me

**Comment by rom4ster** [comment]
plugin crashes on enable if new asar file installed.

**Comment by Robbercall911** [comment]
yea same here, i can reload discord but as soon as i go to settings i crash and it tells me to reload again. if i try joining a call in a server, it says RTC Connecting and never joins

**Comment by Robbercall911** [comment]
https://github.com/BetterDiscord/BetterDiscord/issues/1540 known issue by betterdiscord devs, its nothing to do with any specific plugin. disable plugins by hitting repair in betterdiscord installer and wait for a fix.

**Comment by rom4ster** [comment]
@Robbercall911  either explain what specifically Betterdiscord needs to fix or stop spreading false information. I am able to use many plugins just fine with the patched betterdiscord asar that is provided on the betterdiscord discord, however, Show Hidden Channels is the one plugin that fails. This means that SHC is broken OUTSIDE of betterdiscord, unless have real example (not the one you provided) to prove otherwise, then this is still VERY much an issue.

**Comment by Robbercall911** [comment]
> @Robbercall911 either explain what specifically Betterdiscord needs to fix or stop spreading false information. I am able to use many plugins just fine with the patched betterdiscord asar that is provided on the betterdiscord discord, however, Show Hidden Channels is the one plugin that fails. This means that SHC is broken OUTSIDE of betterdiscord, unless have real example (not the one you provided) to prove otherwise, then this is still VERY much an issue.

i mean you could just say "hey man i dont think this is right." your entitled to your own opinion, but seeing the fact i removed every plugin and reinstalled betterdiscord. this would mean its not the plugin. especially after i installed the new asar file. thank you for your input. ill keep that next to my list of not important. have a good day

**Comment by rom4ster** [comment]
you should also remove themes, but yeah i was harsh, its been a rough day srrz

**Comment by Robbercall911** [comment]
> you should also remove themes, but yeah i was harsh, its been a rough day srrz

all good, we all have our bad moments. no offense taken. i tried removing themes too. i clean wiped everything. i spent like 4 hours checking everything, errors and all. im stumped

**Comment by euromii** [comment]
i uninstalled everything and reinstalled and got discord to stop from crashing. I've been testing plugins one by one and once I try to enable this plugin discord begins to crash again, so even after fixing everything something is also wrong w/ this specific plugin too :)

**Comment by ViLiDi230** [comment]
> plugin crashes on enable if new asar file installed.

but when installed old asar file Better discord didn't launching

**Comment by Amb33r** [comment]
I have the same for me

**Comment by arianwen27** [comment]
There's a fix in the better discord github. Applied that and my discord now works somewhat.

Viewing any server that has hidden channels crashes my discord, servers without hidden channels are fine. Disabling this plugin and viewing the same server works without a crash. This plugin crashes discord when it tries to show a hidden channel.

**Comment by RobotoLev** [comment]
I can confirm that the plugin doesn't work well with the upcoming BD update (there's a patched .asar file in their Discord server). This is the PR at BD github: https://github.com/BetterDiscord/BetterDiscord/pull/1530
That exact patched file fixes crash on opening settings, but some plugins become incompatible (and so this plugin becomes as well).

Something has to be dealt with the frontend part (as I know, upcoming patch fixed something about loading css). The plugin crashes when opening a Discord server, which contains hidden channels.

**Comment by JustOptimize** [comment]
Betterdiscord fucked up the Tooltip 🤦🏻

If you want to switch to Replugged there's a SHC for that thanks to Tharki <3 https://github.com/Tharki-God/ShowHiddenChannels

**Comment by JustOptimize** [comment]
The issue should be fixed with latest release, can anyone confirm?

**Comment by arianwen27** [comment]
Seems to be working for me now

**Comment by Bulkin777** [comment]
> The issue should be fixed with latest release, can anyone confirm?

Bro, how long to expect a fix from you?

**Comment by JustOptimize** [comment]
Btw, still crashes when right clicking servers but who needs that, right?

**Comment by GuillerA11** [comment]
> 

Also crash when you left click a server with hidden channels (but not always, couldn't reproduce it at 100%)

**Comment by arianwen27** [comment]
Right clicking crashes yes

**Comment by Bulkin777** [comment]
+ a notification appears on top that presumably the discord battery has been updated, click here to update, click on it and it crashes

**Comment by JustOptimize** [comment]
The thing when you click on the settings it's caused by betterdiscord (scroll up to see solution)

New discord update broke tooltips, context menus headers and settings, betterdiscord is working on a fix.

**Comment by arianwen27** [comment]
Just in case I need to say it. https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389 this is the fix for the settings crash, just replace this new file with the one currently on your pc. After that, any crashes won't be better discord's fault (hopefully)

**Comment by JustOptimize** [comment]
Oh god, lots of plugins are broken 😨 
![image](https://user-images.githubusercontent.com/54294419/221911630-891d3c2d-0430-40ba-8786-e68aa85a72fe.png)

**Comment by Bulkin777** [comment]
> Just in case I need to say it. https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389 this is the fix for the settings crash, just replace this new file with the one currently on your pc. After that, any crashes won't be better discord's fault (hopefully)

Bro, which folder should I throw the file into?

**Comment by arianwen27** [comment]
C:\Users\YOURNAME\AppData\Roaming\BetterDiscord\data

**Comment by GuillerA11** [comment]
> @GuillerA11 are you sure that it is caused by the SHC plugin? It shouldn't...

My bad, thought only SHC was affected with this, I've checked all plugins 1 by 1 using your broken plugins list and now is stable 100%. Thank you very much

**Comment by arianwen27** [comment]
Right click working, thanks

**Comment by BySwiizen** [comment]
> Hi, I just installed the plugin and it keeps crashing even after restarting. A solution ? ![DiscordCanary_VFpbDczFSN](https://user-images.githubusercontent.com/29678500/221696791-49449384-72b8-4af8-9fb3-44e22463a654.png)

It works!

**Comment by arianwen27** [comment]
exit discord, re open discord. When it crashes, it reloads the server your currently in. Closing and re opening discord brings you to the main on server page. Now update the plugin to v0.2.5, now try a server. If it still crashes, it's something else you have

**Comment by Baebeeee** [comment]
better discord says to me that the plugin is a meta not found, someone knows how to fix?

**Comment by arianwen27** [comment]
Did you copy everything in https://raw.githubusercontent.com/JustOptimize/return-ShowHiddenChannels/main/ShowHiddenChannels.plugin.js ?  The whole thing is required to go into better discord. The meta is the part with the @ symbols at the start.

**Comment by Guonejo** [comment]
![image](https://user-images.githubusercontent.com/82884497/221960125-84ce87e4-fbb1-48b8-b185-ba02674d4dfa.png)

I still can't use BetterDiscord, it crashes every time I try to enter the settings and no plugin works correctly (I tried one by one and it keeps crashing).

**Comment by arianwen27** [comment]
> Just in case I need to say it. https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389 this is the fix for the settings crash, just replace this new file with the one currently on your pc. After that, any crashes won't be better discord's fault (hopefully)
 @Guonejo 
This fixes the crashing issue with settings. The plugin one, there's known bugged plugins that crash rn. Check the list and update this plugin to 0.2.5

**Comment by Guonejo** [comment]
> > Just in case I need to say it. https://github.com/BetterDiscord/BetterDiscord/actions/runs/4290243389 this is the fix for the settings crash, just replace this new file with the one currently on your pc. After that, any crashes won't be better discord's fault (hopefully)
> 
> @Guonejo This fixes the crashing issue with settings. The plugin one, there's known bugged plugins that crash rn. Check the list and update this plugin to 0.2.5 List here https://user-images.githubusercontent.com/54294419/221911630-891d3c2d-0430-40ba-8786-e68aa85a72fe.png originally sent by JustOptimize themselves

I managed to remove the cracking of the settings with the code:

`@echo off
cd %appdata%/betterdiscord/data
taskkill /f /im discord.exe 
curl  https://cdn.discordapp.com/attachments/826217269323235358/1079920833662816277/betterdiscord.asar -O`

But now I have the problem when I right click anywhere in Discord, it crashes.

**Comment by arianwen27** [comment]
The right clicking anywhere thing will probs be a plugin you have. Something will be adding something to your right click menu that's crashing it. Try vanilla better discord (so all plugins off no themes) and see if it still happens

**Comment by Guonejo** [comment]
> The right clicking anywhere thing will probs be a plugin you have. Something will be adding something to your right click menu that's crashing it. Try vanilla better discord (so all plugins off no themes) and see if it still happens

I will try again 1 by 1 the plugins I have, it seems it is the BDFDB library that has problems. Now without plugins everything works fine

**Comment by arianwen27** [comment]
Yeah, for a while BDFDB was problematic, then an update came out a few hours ago

**Comment by Guonejo** [comment]
> Yeah, for a while BDFDB was problematic, then an update came out a few hours ago

![image](https://user-images.githubusercontent.com/82884497/221963446-12cafd7e-7879-43bf-902a-b41fa06fe983.png)

Ok apparently the Volume Boost plugins are the problem, I disabled these two and they loaded all the remaining plugins (at least in my case).
