### ISSUE TITLE
Updater broken

### ISSUE THREAD

**Issue by BGP0** [JustOptimize/return-ShowHiddenChannels#106]
Without announcement, the BD team have silently removed the pluginupdater module to spite plugins they don't like (like plugins that are not on their official website) https://github.com/rauenzi/BDPluginLibrary/commit/1f0697e55d68a71880bcab95e74afb998b8e4196

To fix this, a new plugin updater module will need to be created using fetch() and require("fs") to download and save files. But this will most likely be removed by BD in the future to spite unofficial devs, again :(

Anyone have any ideas on what to do? I would create a fork of BD but I don't have time.

**Comment by BGP0** [comment]
its back temporarily so there will be time to update the program

**Comment by JustOptimize** [comment]
*Spoiler*
![image](https://user-images.githubusercontent.com/54294419/222962160-b6f90737-f8dd-450e-877c-a6af5194a032.png)

**Comment by JustOptimize** [comment]
![image](https://user-images.githubusercontent.com/54294419/222962939-a6134360-f8bc-4485-8d25-87d07ef384fc.png)
![image](https://user-images.githubusercontent.com/54294419/222962958-5e133831-90d8-4e14-a454-acc85f1469b7.png)
![image](https://user-images.githubusercontent.com/54294419/222962970-ef7cd920-10d8-48c6-b935-ce25eb9fbcb5.png)

**Comment by JustOptimize** [comment]
You can now test the updater in the dev branch 9b0c90a.

**Comment by BGP0** [comment]
nice work that code is way better than mine haha
