### ISSUE TITLE
META was not found error

### ISSUE THREAD

**Issue by Aholicknight** [JustOptimize/return-ShowHiddenChannels#108]
![DiscordPTB_20230314_SaToJXVNBZ](https://user-images.githubusercontent.com/7843719/224571552-70af4755-5cb4-4f70-8f25-b27ede10d1ab.png)

I am trying to install the ShowHiddenChannels plugin into discord, and I get this error when trying to load it. How do I fix this message? Thank you!

**Comment by JustOptimize** [comment]
You downloaded the plugin wrong, follow the readme to download it correctly

**Comment by Aholicknight** [comment]
> You downloaded the plugin wrong, follow the readme to download it correctly

Thank you @JustOptimize for your fast reply, I will install it again and hopefully it will be fixed.
