### ISSUE TITLE
Library doesn't run

### ISSUE THREAD

**Issue by DTraitor** [JustOptimize/return-ShowHiddenChannels#11]
I keep getting this message when trying to run `C_BDFDB` with and without a VPN (1.1.1.1)
![image](https://user-images.githubusercontent.com/74188902/190013818-96fabae0-d090-40d5-9e69-b126b53a4fbf.png)
Github itself works

**Comment by JustOptimize** [comment]
What version of the plugin are you using?

**Comment by Banquo88** [comment]
Having the exact same issue, I just copied the code from your page, so what ever version that is... created a new file with Notepad++, pasted the 1BDFDB code from your page, saved it as "1BDFDB.plugin.js", threw it into the plugins folder, then opened up the existing "ShowHiddenChannels" file, pasted your code into it, then tried the plugin again, and got the exact same result/issue.... there are no instructions on how to inject or install your version, so i had to guess that this was the correct way

**Comment by ArthixFR** [comment]
I think you have to copy the files in the `_res` folder of the archive to the `plugins` folder of BetterDiscord. I have the same problem and I solved it by doing this :)

**Comment by JustOptimize** [comment]
> here are no instructions on how to inject or install your version

Sorry for the delayed responce, to install the plugin you should put the ShowHiddenChannels.plugin.js file in the plugins folder.
If you don't have the C_BDFDB/1BDFDB library installed it will prompt to install it automatically

> I think you have to copy the files in the _res folder of the archive to the plugins folder of BetterDiscord. I have the same problem and I solved it by doing this :)

This doesn't make much sense since the plugin already downloads the file it needs and puts them in the plugins folder

**Comment by JustOptimize** [comment]
> I think you have to copy the files in the `_res` folder of the archive to the `plugins` folder of BetterDiscord. I have the same problem and I solved it by doing this :)

I had messed up the download link with the last library update, thanks <3
