### ISSUE TITLE
Doesnt work (It shows the hidden channels, but not whats in it

### ISSUE THREAD

**Issue by githubmaon** [JustOptimize/return-ShowHiddenChannels#111]
It doesnt show whats in the channel it just shows the permissions required to see it.

**Comment by JustOptimize** [comment]
It's written litterally everywere that this plugin will not allow you to see the channel messages
In the readme:
![image](https://user-images.githubusercontent.com/54294419/225747036-1e5df4dd-db96-40e6-a8de-afebde9fd9b9.png)
In the plugins tab:
![image](https://user-images.githubusercontent.com/54294419/225747108-4a9074c9-e9a2-4f73-b203-f52cfd5d34d0.png)
