### ISSUE TITLE
Discord crash

### ISSUE THREAD

**Issue by Tondaztratilbonga** [JustOptimize/return-ShowHiddenChannels#112]
Every time when i put new show hiden channels my discord crashing

**Comment by fedebartoli** [comment]
same

**Comment by Bulkin777** [comment]
![image](https://user-images.githubusercontent.com/39707951/227636113-55c1bafc-52ac-490c-a95d-4a702af63cbe.png)
I actually moved to discord, or rather I tried, and I'm also experiencing a discord crash

**Comment by JustOptimize** [comment]
I spent an entire afternoon trying to fix this problem until I opened betterdiscord's discord and discovered that the problem is theirs and not the plugin's.

**Comment by JustOptimize** [comment]
Betterdiscord fixed with latest release, go download it now!
