### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by svuddi** [JustOptimize/return-ShowHiddenChannels#113]
It's just not working anymore since yesterday's update.
Error title : An error was encountered while trying to load this plugin.

Error details : "A plugin which displays all hidden Channels, which can't be accessed due to Role Restrictions, this won't allow you to read them (impossible)."

![image](https://user-images.githubusercontent.com/128890517/227704688-574f3517-d777-4f33-899b-acd0a4a43831.png)

**Comment by JustOptimize** [comment]
I can't replicate, do you see any error in the console?

**Comment by Bulkin777** [comment]
I just opened the existing installation of BetterDiscord itself, after which the new version sign appeared, I clicked later, and did the usual Repair of BetterDiscord, and everything works without crashes with the rest of the plug-ins
