### ISSUE TITLE
Plugin Takeover Request - Message Logger

### ISSUE THREAD

**Issue by ResidentSpaceDragon** [JustOptimize/return-ShowHiddenChannels#115]
Lightly like most BD devs they "no longer have time" for any projects despite over 7 months of time to work on projects since the massive discord break last year. Lighty has blocked any way to communicate both on github and on discord and no longer seems interested in supporting the plugin despite massive requests for it
Would you be interested in taking over the plugin and bringing it up to date as you did with SHC?
https://github.com/1Lighty/BetterDiscordPlugins/tree/master/Plugins/MessageLoggerV2
There is a code "update" that no longer works in his discord,for a better starting block

**Comment by JustOptimize** [comment]
There is already a working version (https://github.com/Davilarek/MessageLoggerV2-fixed)
