### ISSUE TITLE
(Bug) Unknown Users being ignored from hidden channel page

### ISSUE THREAD

**Issue by E-enuts** [JustOptimize/return-ShowHiddenChannels#116]
Ok, So if i dm an person it should show the user thing i think 

![image](https://user-images.githubusercontent.com/117570481/229343370-a1f90df5-d019-4704-ab23-8b1ef23e9572.png)
![image](https://user-images.githubusercontent.com/117570481/229343382-fbc1aabb-8d7f-4173-a12d-0c5317efa132.png)
![image](https://user-images.githubusercontent.com/117570481/229343422-1ef3fd8e-bd37-4b72-96b1-1d881dca64f7.png)

(Its an lil issue if you got time you can fix it i think)

What i mean ->>> 
![image](https://user-images.githubusercontent.com/117570481/229343503-4c9ddb68-d934-4b7b-8c85-439eda985908.png)

**Comment by E-enuts** [comment]
So if you can fix it huge W

**Comment by JustOptimize** [comment]
Fixed next release with commit afa3b22

If you want to test this you can download the dev version [here](https://raw.githubusercontent.com/JustOptimize/return-ShowHiddenChannels/dev-unstable/ShowHiddenChannels.plugin.js)
