### ISSUE TITLE
(Bug) Native sorting broken, all hidden channels are at the bottom of the channel list

### ISSUE THREAD

**Issue by ResidentSpaceDragon** [JustOptimize/return-ShowHiddenChannels#117]
Native sorting seems to be broken as of latest updates. Deleting the config file and restarting, all hidden channels are at the bottom of the channel list even with the native sorting default option selected and without touching any settings from the default shipped

**Comment by JustOptimize** [comment]
I'm currently waiting for the update. We'll see

**Comment by ResidentSpaceDragon** [comment]
Stable 185832 (29333f6)
0.0.26
I hadent updated discord or betterdiscord in a while till the other day but the issue is present in stable canary and ptb

**Comment by JustOptimize** [comment]
I'm on Ptb 185877 and everything is working fine so the issues shouldn't be the "update".
Can you send me a copy of your `ShowHiddenChannels.config.json`?

**Comment by ResidentSpaceDragon** [comment]
```
{
    "currentVersionInfo": {
        "version": "0.2.7",
        "hasShownChangelog": true
    }
}
```

**Comment by JustOptimize** [comment]
The config seems right, what os are you using? (Linux, Windows, Mac)

**Comment by ResidentSpaceDragon** [comment]
Linux

**Comment by JustOptimize** [comment]
Discord on Linux and Discord on Windows are different; both versions have the same core features but they work differently one from the other, I don't think I can fix this since I'm not even touching the channel order when patching.

I had to switch back to windows when coding this plugin because some issues just weren't happening on Linux so I was getting issues from windows users. (Ex: #53 )
In your case it's appening the exact opposite. 🤷🏻 

Keep me updated if it fixes itself

**Comment by ResidentSpaceDragon** [comment]
Pushed random config buttons till it went back to the way it was before

```
{
    "currentVersionInfo": {
        "version": "0.2.7",
        "hasShownChangelog": true
    },
    "settings": {
        "hiddenChannelIcon": "lock",
        "sort": "native",
        "showPerms": true,
        "showAdmin": "channel",
        "MarkUnread": false,
        "alwaysCollapse": true,
        "shouldShowEmptyCategory": true,
        "debugMode": false,
        "channels": {
            "GUILD_TEXT": true,
            "GUILD_VOICE": true,
            "GUILD_ANNOUNCEMENT": true,
            "GUILD_STORE": true,
            "GUILD_STAGE_VOICE": true,
            "GUILD_FORUM": true
        },
        "blacklistedGuilds": {}
    }
}
```

**Comment by JustOptimize** [comment]
> Pushed random config buttons till it went back to the way it was before

If you don't change the default settings it will use the default config and it will not be saved in the config file (as expected)

**Comment by JustOptimize** [comment]
Today i booted back to linux just to find out that everything is working

**Comment by JustOptimize** [comment]
At least it isn't something related to it being linux only

**Comment by JustOptimize** [comment]
> and aur packages for the other variations

What you mean with that? Discord variations? Os variations?

Another queston, do you user other plugins? (Is so, what)

**Comment by ResidentSpaceDragon** [comment]
> > and aur packages for the other variations
> 
> What you mean with that? Discord variations? Os variations?

discord-canary,discard-ptb and discord-developement are not official packages supported by the distro managers and are are only found in the AUR (user repo) for install

> Another queston, do you use other plugins? (if so, what)

I honestly dont know what is and isnt working since the big discord update last year seeing how most bd devs are lazy fucks with lame excuses as  to why they havent been able to update a plugin in over 6 months so this is just a ls dump of whats in the plugins folder
```
0BDFDB.plugin.js
0PluginLibrary.plugin.js
1XenoLib.plugin.js
ActivityIcons.plugin.js
APlatformIndicators.plugin.js
AutoScroll.plugin.js
BetterFormattingRedux.plugin.js
BetterFriendList.plugin.js
BetterRoleColors.plugin.js
BetterSearchPage.plugin.js
CallTimeCounter.plugin.js
ChannelsPreview.plugin.js
CharCounter.plugin.js
ClickableMentions.plugin.js
CompleteTimestamps.plugin.js
DoubleClickToEdit.plugin.js
EditChannels.plugin.js
EditRoles.plugin.js
EditServers.plugin.js
EditUsers.plugin.js
EmoteReplacer.plugin.js
ForceImagePreviews.plugin.js
FreeStickers.plugin.js
FriendNotifications.plugin.js
GameActivityToggle.plugin.js
HideDisabledEmojis.plugin.js
HideMutedCategories.plugin.js
ImageUtilities.plugin.js
InAppNotifications.plugin.js
InvisibleTyping.plugin.js
KeepCurrentChannel.plugin.js
KeywordTracker.plugin.js
LastMessageDate.plugin.js
MessageLoggerV2.plugin.js
MessageUtilities.plugin.js
NotificationSounds.plugin.js
PermissionsViewer.plugin.js
PersonalPins.plugin.js
PinnedMessageIcons.plugin.js
RemoveBlockedUsers.plugin.js
RemovedConnectionAlerts.plugin.js
removeTrackingURL.plugin.js
ReplaceTimestamps.plugin.js
RoleFilter.plugin.js
RoleMembers.plugin.js
RoleMentionIcons.plugin.js
ServerDetails.plugin.js
ShowAllActivities.plugin.js
ShowConnections.plugin.js
ShowHiddenChannels.plugin.js
SpellCheck.plugin.js
SplitLargeMessages.plugin.js 
StaffTag.plugin.js
StatusEverywhere.plugin.js
ThemeRepo.plugin.js
TypingUsersPopouts.plugin.js
UnreadCountBadges.plugin.js
UserNotes.plugin.js
VoiceActivity.plugin.js
VoiceUnreadIndicators.plugin.js
```

**Comment by JustOptimize** [comment]
> discord-canary,discard-ptb and discord-developement are not official packages supported by the distro managers and are are only found in the AUR (user repo) for install

And you are using betterdiscord on all of them and the issue is there for all of them, right?

> I honestly dont know what is and isnt working since the big discord update last year seeing how most bd devs are lazy fucks with lame excuses as to why they havent been able to update a plugin in over 6 months so this is just a ls dump of whats in the plugins folder

Try moving everything except SHC to a temporary dir and restart discord and check if the issue persists, if that doesn't work try using flatpack

By the way, you seem to be the laziest one here, not checking every plugin and their repos to make sure they are up to date.
You're using 60 plugins and between banned and broken plugins, it's a miracle discord is still working
