### ISSUE TITLE
(Bug) Right click disappear explenation

### ISSUE THREAD

**Issue by E-enuts** [JustOptimize/return-ShowHiddenChannels#118]
![image](https://user-images.githubusercontent.com/117570481/229992952-0466209d-e060-4c8d-a6e0-1649d0229c0f.png)

**Comment by JustOptimize** [comment]
Thanks for the info 👍🏻

**Comment by JustOptimize** [comment]
Fixed: https://github.com/BetterDiscord/BetterDiscord/releases/tag/v1.9.2
