### ISSUE TITLE
(Enhancement)let the user can  read (or read and send) in hidden channels

### ISSUE THREAD

**Issue by player10783** [JustOptimize/return-ShowHiddenChannels#121]

**Comment by JustOptimize** [comment]
I swear I'm losing faith in humanity

**Comment by player10783** [comment]
> 

hmmmm

**Comment by JustOptimize** [comment]
![image](https://user-images.githubusercontent.com/54294419/234021678-de847ba6-01f3-44ec-a107-6a1156b4bea8.png)
or
![image](https://user-images.githubusercontent.com/54294419/234021777-8719eb86-2792-48e2-9b49-151b3c68e845.png)
