### ISSUE TITLE
Does this plugin work on Community-Enabled servers?

### ISSUE THREAD

**Issue by MrPigeontheCoder** [JustOptimize/return-ShowHiddenChannels#124]
I'm in a server that has Community enabled, which activates that annoying thing "View Channels & Roles", and i installed this plugin and wanted to know if it worked, because it didn't show any hidden channels whatsoever...

**Comment by JustOptimize** [comment]
Yes, it works on Community-Enabled servers too, for them you will need to right click the guild icon and enable `show all channels (new)` di disable the select the `channels you want to see` feature or enable each channel in that menu
