### ISSUE TITLE
(Bug) Server Context menu not working

### ISSUE THREAD

**Issue by jozsaVilmos** [JustOptimize/return-ShowHiddenChannels#125]
Hi!

Plugin stopped working today, Show All Channels button just shows some random locked channels, Disable SHC button dissapeared from everywhere.

**Comment by JustOptimize** [comment]
Unfortunatly no, you will need to delete your config file or remove the gluilds from it. You can delete the file (easier) by closing discord, go to %appdata%/BetterDiscord/plugins and delete ShowHiddenChannels.config.json, now you can open discord again

**Comment by JustOptimize** [comment]
I just pushed a quick fix in the dev-unstable branch (The blacklisted guilds setting should work)
To apply this fix replace the plugin file with [this one](https://raw.githubusercontent.com/JustOptimize/return-ShowHiddenChannels/dev-unstable/ShowHiddenChannels.plugin.js)

**Comment by ilan0098** [comment]
The context menu problem is currently a BD problem , it has nothing to do with the plugin itself

**Comment by JustOptimize** [comment]
> The context menu problem is currently a BD problem , it has nothing to do with the plugin itself

Emm... already said that?

**Comment by JustOptimize** [comment]
Fixed with the latest BetterDiscord update
