### ISSUE TITLE
(BUG) Can't select Voice Channels

### ISSUE THREAD

**Issue by elisBarovsky** [JustOptimize/return-ShowHiddenChannels#131]
hey, before the last update - I could see allowed users in the voice and text channels. now I can see only for text channels...
what happened ?):

**Comment by JustOptimize** [comment]
Oh discord broke it again, will be fixed soon, thanks for noticing.

Last update discord broke voice channels (Fixed with v0.3.0), now they broke them again...

**Comment by JustOptimize** [comment]
Found the issue and created a fix

**Comment by JustOptimize** [comment]
Made the fix more reliable and cleaner, could anyone confirm this [Dev version with fix](https://raw.githubusercontent.com/JustOptimize/return-ShowHiddenChannels/dev-unstable/ShowHiddenChannels.plugin.js) is working?

**Comment by JustOptimize** [comment]
Tested on different servers, uploaded to main v0.3.1 (Restart discord to check for updates)
