### ISSUE TITLE
Doesn't work for certain community and partnered servers.

### ISSUE THREAD

**Issue by Elite352** [JustOptimize/return-ShowHiddenChannels#139]
I have noticed, that this plugin doesn't work for certain servers. Some servers which are private, and I cannot invite people to. This is only an issue on some community servers. The easiest one I can point out is the official iOS Cowabunga server. I know these servers have channels which I cannot see. When I go to "channels & roles" if I uncheck a channel from there, it will not show up at all with the plugin working. The thing is, some servers have chats for specific languages for which you need a role to access and those do not show up on the browse channels page. Meaning they probably have more channels, such as a staff chat, booster chat, etc. Which will not show up in the browse channels page meaning I cannot see them at all. As far as I've noticed, this only happens if a channel is not clicked in the browse channels page on any community or partnered server. I managed to recreate this in a server I created and moved to a community server. I'm not sure if it can be fixed, but community servers are now patching this plugin. (Accidentally posted this in discussions at first. Whoops. Sorry.)

**Comment by JustOptimize** [comment]
Have you checked "Show all channels" by right clicking the server icon?

**Comment by Elite352** [comment]
I had it clicked yes. This morning my discord updated, and I had to reinstall BD. Ever since then it's been working. Probably has to do with something else not the plugin it's self. Thanks.
