### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by hugruhguerfjnsdfsrt** [JustOptimize/return-ShowHiddenChannels#140]
An error was encountered while trying to load this plugin.
A plugin which displays all hidden Channels, which can't be accessed due to Role Restrictions, this won't allow you to read them (impossible).

**Comment by JustOptimize** [comment]
Hi, have you followed the install instructions in the readme file? https://github.com/JustOptimize/return-ShowHiddenChannels#how-to-install

**Comment by MysteriousLychee** [comment]
I am also having  the same issue.

**Comment by hugruhguerfjnsdfsrt** [comment]
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/148921117/36ae49ed-11fe-4220-882d-f1cfcb879c44)
this is what comes up

**Comment by hugruhguerfjnsdfsrt** [comment]
does not let me download it and I've had this plugin for months

**Comment by hugruhguerfjnsdfsrt** [comment]
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/148921117/1e167d10-45aa-4e58-9840-326ff02bb694)

**Comment by hugruhguerfjnsdfsrt** [comment]
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/148921117/d345db40-f108-4cc9-bbbf-7ccac79a3c9d)

**Comment by cheese529** [comment]
I am also having this same issue..

**Comment by XHesaX** [comment]
same

**Comment by yu06100** [comment]
I am also having this same

**Comment by Wendy4224** [comment]
Same

**Comment by Wendy4224** [comment]
Probably it`s because new **discord** update lol

**Comment by GoaConstrictor** [comment]
> Probably it`s because new **discord** update lol

I have the same issue after the last DC update.. let´s hope the plugins will updated as well in the near future.

**Comment by JustOptimize** [comment]
I just got the update, I'll start working on it asap

**Comment by babynice** [comment]
we are waiting for a fix!  thx

**Comment by angrybirdice** [comment]
agreed waiting

**Comment by hugruhguerfjnsdfsrt** [comment]
awesome thank u! how long will a fix take?

**Comment by BlackTea1337** [comment]
agreed waiting

**Comment by JustOptimize** [comment]
Just give a 👍 to the original topic, the "agreed " spam is actively unhelpful (same for the issue in Zerebos library's repo)

**Comment by FrimenMaj03** [comment]
👍

**Comment by JustOptimize** [comment]
SPOILER: 
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/54294419/c84a31e9-2eb6-431b-b440-e14c35e985c2)

**Comment by JustOptimize** [comment]
discord started crashing when opening the console so for now i'll be releasing a limited version with less features until i can fix that

**Comment by aloopakoda** [comment]
![zeres](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/148954268/2c9a7335-4d62-4223-878d-d85288bd8223)
![ShowHiddenChannels](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/148954268/8cb7967d-dd37-4dbf-9894-5d31897ad756)

**Comment by JustOptimize** [comment]
Well, I didn't release the patched version yet, wait 1 sec

**Comment by JustOptimize** [comment]
update: fixed the crashing i was having when opening the console, nice

**Comment by JustOptimize** [comment]
Released: 1af5586a68afe60624f205ab0039acf2669961f1

**Comment by JustOptimize** [comment]
Known Issues:
- Settings (Library's fault)
- Topic
- Roles

**Comment by aloopakoda** [comment]
Its working! Thank You so much!

**Comment by velg1** [comment]
Still not working,  pluginlibrary still not working

![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/149176825/c7f4b09b-a4f2-47c0-87e0-19a34c9b1804)

**Comment by JustOptimize** [comment]
mr, I'm not the author of the library, I'm the author of ShowHiddenChannels.

**Comment by angrybirdice** [comment]
> mr, I'm not the author of the library, I'm the author of ShowHiddenChannels. the library has some issues but it still works for what I need it to do except for stuff like changelogs

just take your time no need to rush with the plugin. I had seen the library went down like discord made changes to it's code

**Comment by ButterMySlug** [comment]
Zere's just went ahead and fixed their plugin as a heads up.

![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/84187812/6fe48d65-c778-464f-8098-e7f7bdcf5b68)

**Comment by Chiaying27** [comment]
<img width="504" alt="image" src="https://github.com/JustOptimize/return-ShowHiddenChannels/assets/167046804/b7942a97-5985-4599-b66a-7c6542917d5d">
what is this problem? If I clicked start anyway, it still didnt function

**Comment by JustOptimize** [comment]
Wrong issue my guy, you're looking for #188

**Comment by zofiell** [comment]
hola buenas tardes.   hoy me salio el mismo error que a los demas
<img width="504" alt="341014177-b7942a97-5985-4599-b66a-7c6542917d5d" src="https://github.com/JustOptimize/return-ShowHiddenChannels/assets/173303072/201f14f0-12cf-4e4c-a786-d762f97436cf">

**Comment by zofiell** [comment]
tengo el mismo error me salio hoy que es 19-07-24
