### ISSUE TITLE
(ZeresPluginLibrary) "Plugin Constructor() could not be fired"

### ISSUE THREAD

**Issue by Gandiiiii** [JustOptimize/return-ShowHiddenChannels#144]
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/149255742/f5e4aa7e-7954-4d74-a46a-642b2d6323f0)
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/149255742/b9c08173-5493-4bc7-8aa7-4954921b3419)

I've followed the way you should read me inside gifhub, but still get it

**Comment by JustOptimize** [comment]
That's ZeresPluginLibrary, not my plugin.
The author of that library is working on it, in the meantime you won't be able do recive automatic updates and see the changelog popup for ShowHiddenChannels.

**Comment by JustOptimize** [comment]
Library has been fixed
