### ISSUE TITLE
ShowHiddenChannels not working 

### ISSUE THREAD

**Issue by Breetlez** [JustOptimize/return-ShowHiddenChannels#145]
![DiscordPTB_RBM6bUC3ZS](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/45339747/9fc555e3-dc51-4a9a-bb52-41d9979434d8)

**Comment by jack-glenn** [comment]
Same issue :(

**Comment by JustOptimize** [comment]
This has been fixed, check #140.

TLDR: Download the new version
