### ISSUE TITLE
Not working in most recent better discord update (v1.9.5)

### ISSUE THREAD

**Issue by gmanc2** [JustOptimize/return-ShowHiddenChannels#147]
In the most recent better discord update it seems to have broken the plugin. I'm using the most recent build from two days ago and it says meta not found. Here is the log on startup: [log](https://gist.github.com/gmanc2/9cd60c07f61456afa8f3b3513af908e1)

**Comment by JustOptimize** [comment]
It seems to be #114

**Comment by gmanc2** [comment]
Very weird, I installed it like 3-4 times the same way that is in the instructions then I restarted my PC and redownloaded it added an extra character at the end and it worked.
