### ISSUE TITLE
Not working with DIscord on new update

### ISSUE THREAD

**Issue by TheMin3s** [JustOptimize/return-ShowHiddenChannels#151]

**Comment by JustOptimize** [comment]
Hi, thank you for reporting this issue, can you elaborate more on your statement? (Perhaps sending a screenshot of the error)

**Comment by gbhb** [comment]
@JustOptimize 
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/46089146/806fa484-de0e-41f7-90e5-5b84bc60d5f1)
thank you for taking the time to fix the bug

**Comment by JustOptimize** [comment]
Hi, this issue has been fixed a week ago @gbhb. Maybe it's a new one, who knows 🤷🏻‍♂️...
Let's wait for @TheMin3s response

**Comment by TheMin3s** [comment]
Sorry for taking so long to respond.
BetterDiscord doesn't let me see the error log for some reason, all it lets me see is this message when looking at it in the plugins list
<img width="640" alt="Screenshot 2023-11-02 at 10 21 45 PM" src="https://github.com/JustOptimize/return-ShowHiddenChannels/assets/128933564/655e7bd5-ad45-4c79-9eb1-a8fd076c696e">
I'm on mac, so this could be an OS-specific issue.

**Comment by MofumofuChan** [comment]
Your version is v0.2.8. Download the new version which is v0.3.5. That one fixes this issue

**Comment by TheMin3s** [comment]
Oh, I never realized, it started working again
Thanks lol
