### ISSUE TITLE
Separate category sorting not working

### ISSUE THREAD

**Issue by JPXR** [JustOptimize/return-ShowHiddenChannels#152]
Okey so when choosing from Sorting Order "Hidden Channels in a separate Category at the bottom". It will only do that for discord servers i am owner/admin where i can aldeary see all the channels. But for other servers it just keeps the channels in the Default Sort order.

**Comment by JustOptimize** [comment]
Can you share your config file? It's working for me...

**Comment by JPXR** [comment]
[ShowHiddenChannels.config.json](https://github.com/JustOptimize/return-ShowHiddenChannels/files/13257119/ShowHiddenChannels.config.json)
There you go

**Comment by JustOptimize** [comment]
Still working with the same config...interesting... are you avaiable for a call? If so add me on discord (tag: oggetto)

**Comment by JPXR** [comment]
I gotta go in a bit but i did manage to fix it by going back to the 0.3.5 version of ShowHiddenChannels.

**Comment by JustOptimize** [comment]
v0.3.6 was bugged indeed, thanks for reporting, will be fixed in the next release

**Comment by JustOptimize** [comment]
If you got a minute, can you check if this version works?
https://raw.githubusercontent.com/JustOptimize/return-ShowHiddenChannels/dev-unstable/ShowHiddenChannels.plugin.js

**Comment by JPXR** [comment]
Yes this is working 👍
