### ISSUE TITLE
doesnt work anymore

### ISSUE THREAD

**Issue by kneekicker** [JustOptimize/return-ShowHiddenChannels#159]
doesnt work anymore

**Comment by ProjectEzy** [comment]
up

**Comment by JustOptimize** [comment]
tried on Fedora, Windows 10 and on Bettervencord, it works on all of them

**Comment by JustOptimize** [comment]
Still working and same bd version.
What discord version do you have?

**Comment by JustOptimize** [comment]
I have the same discord version and host version and it is woring... 🤔 
Are you sure you have the latest plugin version? (>= 0.3.8)
