### ISSUE TITLE
Compatibility with new Discord update

### ISSUE THREAD

**Issue by edurmt** [JustOptimize/return-ShowHiddenChannels#16]
With the new Discord update, breaking majority of plugins across all client mods, will you be updating the plugin, or will this plugin become a relic of the past?

**Comment by JustOptimize** [comment]
I will try to solve the problem, but at the moment I am waiting for Devil to fix his library.

**Comment by Squishyzbear** [comment]
just an fyi devilbro updated his library

**Comment by MisileLab** [comment]
devilbro updated library, we can use devilbro's library for updating
