### ISSUE TITLE
(BUG) Not respecting collapsed categories on "bottom" sorting order

### ISSUE THREAD

**Issue by Gpax971** [JustOptimize/return-ShowHiddenChannels#160]
When using "Hidden channels at bottom of category" sorting order, channels are always shown, even if the category is collapsed. 

The `sortChannels` function ignores if the category is collapsed, and so will always render the channels, regardless of if the category is collapsed or not. A fix I found is to change line 1345 from
```
        if (!category) return;
```
to
```
        if (!category || category.isCollapsed) return;
```

**Comment by JustOptimize** [comment]
Thanks, will be fixed next release!
