### ISSUE TITLE
dont work for me

### ISSUE THREAD

**Issue by mahdikhodsiani** [JustOptimize/return-ShowHiddenChannels#161]
![Screenshot (250)](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/45894288/d27f3d48-2c3e-4671-a654-a83c8c030e07)

**Comment by JustOptimize** [comment]
try updating the plugin

**Comment by mahdikhodsiani** [comment]
i use last version

**Comment by mahdikhodsiani** [comment]
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/45894288/959246c2-6832-485c-aaeb-fa1a61cbf44b)

**Comment by JustOptimize** [comment]
Can you copy-paste the full error? It seems to be some betterdiscord related error to me, have you tried reinstalling it?

**Comment by mahdikhodsiani** [comment]
fixed . thank you
