### ISSUE TITLE
Rate limit & needed fix

### ISSUE THREAD

**Issue by E-enuts** [JustOptimize/return-ShowHiddenChannels#163]
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/117570481/bfdb58b7-b586-4c01-b826-46eb17d32a8f)
the new update that there was seems to have a flew that is that it has a rate limit if u check a said amount of channel or u do it with a said amount of speed , no i was clicking off and other stuff still same issue
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/117570481/74b1eefd-2b57-400b-bea3-a015c401051e)

**Comment by JustOptimize** [comment]
Fixed in the next release, thanks for reporting it
If you wanna do me a favor and test it download this dev-unstable version: https://raw.githubusercontent.com/JustOptimize/return-ShowHiddenChannels/ba43717daad1b158308e853e1e3079705d0178b0/ShowHiddenChannels.plugin.js
