### ISSUE TITLE
(Bug) Users missing from hidden channel page

### ISSUE THREAD

**Issue by E-enuts** [JustOptimize/return-ShowHiddenChannels#166]
Now the issue is sometimes when i check channels for fun cause of thier names this happens
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/117570481/e8615989-6507-41ed-b7e8-38dd26f2e2af)
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/117570481/1b0fb47e-83cb-4035-aaaf-009a6c325fb6)
the issue is that it dosent show that "the person" is enabled to see the channel

**Comment by JustOptimize** [comment]
I checked multiple servers an I can't replicate, can you try on other servers?
If not, can you send me an invite to that specific server? (Discord tag: @ oggetto)

**Comment by JustOptimize** [comment]
PS: Can you check if mnhg_27967 and Tickets actually have the View Channel permission?

**Comment by JustOptimize** [comment]
Can't repro
