### ISSUE TITLE
(SHC) Broken Modules

### ISSUE THREAD

**Issue by LavenderAndChamomile** [JustOptimize/return-ShowHiddenChannels#167]
Just had this error when Discord opened -

I have chosen "cancel" for now.
![error](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/98702148/947107bd-7dd8-428e-b576-bdfcc84a2930)

**Comment by marto05** [comment]
Same issue

**Comment by JustOptimize** [comment]
Fixed with v0.4.2, thanks for reporting the issue
