### ISSUE TITLE
Discord crashes when clicking on a hidden channel

### ISSUE THREAD

**Issue by Big-Barry** [JustOptimize/return-ShowHiddenChannels#170]
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/60559635/0b631ac6-121c-418c-a9f0-0d0638c0c985)

**Comment by JustOptimize** [comment]
Does this happends on every hidden channel or just a specific one?
What discord version do you have? (check bottom left in settings)

**Comment by Big-Barry** [comment]
accidently closed it mb

**Comment by Big-Barry** [comment]
my bad 
Currently running canary 273760 (d502c7a)

**Comment by Salty-Coder** [comment]
Pretty sure it must be a conflict with the new build of Canary.
I'm having this issue too.
Hidden channels are displayed, but clicking on them causes Discord to crash.

**Comment by JustOptimize** [comment]
As a temp fix, switch to a stable build or disable "Show Permissions" in the plugin's settings.

`props.guild.roles` seems to be undefined so it yeets an error when trying to read the role.id from it
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/54294419/b0c93ca6-bc6d-4bbb-a7e2-216b833297a0)

**Comment by testeraccount192** [comment]
Where do you go to disable show permissions?

Also if you disable show permissions doesn't that defeat the purpose since you can't see who has access to that channel?

**Comment by testeraccount192** [comment]
I tried to download an old version of discord. Then I tried putting discord better but it can't seem to find the old version of discord that I just downloaded.

**Comment by testeraccount192** [comment]
> This also started happening to me on the stable build, 273850 (477ea08). Disabling show permissions fixes it on that too.

Hey I'm not very good with discord...is there a way to show permissions via inspect element on google chrome? Like some way to see who has access to the channel? I'll manually do that for the time being until the plugin is fixed.

Will the plugin get fixed or is this something on discords end and they patched it?

**Comment by JustOptimize** [comment]
> Where do you go to disable show permissions?
> 
> Also if you disable show permissions doesn't that defeat the purpose since you can't see who has access to that channel?

You can still see the hidden channel (the actual purpose of this plugin)

**Comment by JustOptimize** [comment]
> Will the plugin get fixed or is this something on discords end and they patched it?

It will be fixed

**Comment by JustOptimize** [comment]
Pushed a patch to prevent crashing, restart discord and update the plugin

**Comment by testeraccount192** [comment]
> > Where do you go to disable show permissions?
> > Also if you disable show permissions doesn't that defeat the purpose since you can't see who has access to that channel?
> 
> You can still see the hidden channel (the actual purpose of this plugin)

I'm so use to having that extra bit of access to see which roles/users have access to that hidden channel. Is there a temp way to do this for now? Like a way I can do it on google chrome?

**Comment by testeraccount192** [comment]
> Pushed a patch to prevent crashing, restart discord and update the plugin

Yep, I just tested this out now, the crashing stopped. I can see the hidden channels and the time stamp of people speaking in them - just can't see who has access to those channels (for now). You said this can be fixed? Like it's not discord fully patching it? 🙏

**Comment by testeraccount192** [comment]
Commenting on behalf of my other friends - 

Is there another way we can view who's inside of the channel? Like a temporary fix while you work on it?

Really love this feature. Is there anything we can do to help you out? I know you don't have a lot of time.

**Comment by traviscole1** [comment]
ik its hard to fix it fast opti but please if u could fix it asap to see members with permission sorry to bother

**Comment by testeraccount192** [comment]
You said "need to get roles somehow"

Do you think this is now server sided and discord fixed it? Or is it still possible but you just need time to get it fixed?

**Comment by JustOptimize** [comment]
User permissions are now back (dev-unstable version), the only thing that is missing are the roles

**Comment by testeraccount192** [comment]
> User permissions are now back (dev-unstable version), the only thing that is missing are the roles

How do I get the dev-unstable version? been googling it for past 10 minutes and can't seem to find that version of discord

**Comment by JustOptimize** [comment]
Not unstable version of discord, unstable of ShowHiddenChannels, here https://github.com/JustOptimize/return-ShowHiddenChannels/blob/dev-unstable/ShowHiddenChannels.plugin.js

**Comment by testeraccount192** [comment]
You are a legend! It's working!

**Comment by JustOptimize** [comment]
Found a way to get roles

**Comment by JustOptimize** [comment]
Spoiler: 
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/54294419/b4a154e5-c4cc-4aab-adc7-a936132e084a)

**Comment by JustOptimize** [comment]
Fixed with c5de442e8664feb698158a80d2d7bfd3a8c59e98

**Comment by testeraccount192** [comment]
Is there a way I can DM you on here?

**Comment by JustOptimize** [comment]
> JustOptimize or you got like a discord?

Discord: oggetto

**Comment by traviscole1** [comment]
> User permissions are now back (dev-unstable version), the only thing that is missing are the roles

ty so much mate <3 and im waiting for the roles when ur free <3
