### ISSUE TITLE
member access to a certain channel not being displayed

### ISSUE THREAD

**Issue by authies** [JustOptimize/return-ShowHiddenChannels#172]
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/163065687/b1b26704-c25a-42b6-961b-9829a7328c4e)

the feature that showed users who were able to access a channel is no longer being displayed

**Comment by authies** [comment]
ive restarted discord, reinstalled betterdiscord, tried on multiple channels nothing has changed

**Comment by JustOptimize** [comment]
It has been disabled temporally to prevent crashing, see #170

**Comment by authies** [comment]
> It has been disabled temporally to prevent crashing, see #170

ok thanks any eta on when this feature will be back?

**Comment by JustOptimize** [comment]
> ok thanks any eta on when this feature will be back?

not really, don't have much free time

**Comment by traviscole1** [comment]
> > ok thanks any eta on when this feature will be back?
> 
> not really, don't have much free time

ik its hard to fix it fast opti but please if u could fix it asap to see members with permission sorry to bother
