### ISSUE TITLE
Hello, can add new feature?

### ISSUE THREAD

**Issue by Fandyfr** [JustOptimize/return-ShowHiddenChannels#174]
add show hidden chat too, if possible hehehe

**Comment by JustOptimize** [comment]
You can't, you would know if you read the plugins description and this repositoy's readme :/
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/54294419/c42965f2-8cf7-4dbe-894a-72a7ac6233b0)
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/54294419/a89a0042-a800-4cd2-a4ed-45f3213d08f6)
