### ISSUE TITLE
ShowHiddenChannels has detected that some modules are broken (newest version)

### ISSUE THREAD

**Issue by Lemonsniffer9000** [JustOptimize/return-ShowHiddenChannels#175]
I downloaded it a few hours ago and it was working fine, but then I closed discord and reopened it and it's giving me the following errors. I went to a similar post and tried older versions, as well as deleting and uninstalling betterdiscord and the plugin, but there's still an issue.
![Screenshot 2024-03-29 230502](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/152203123/0a37c181-c377-4793-af1f-5540805e0fe8)
![Screenshot 2024-03-29 230509](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/152203123/6134242a-9f03-4be1-8a62-0dfd7e707327)

**Comment by JustOptimize** [comment]
are you on canary?

**Comment by Alexcandert** [comment]
yeah same

**Comment by AsgoreChara666** [comment]
Route in line 161 is undefined.

**Comment by JustOptimize** [comment]
It's 4AM so probably gonna have a look at it tomorrow as soon as possible.

**Comment by Lemonsniffer9000** [comment]
> are you on canary?

no.

**Comment by Lemonsniffer9000** [comment]
also when i press start anyway it works it just doesnt show all the channel data like who can see it last message sent etc. it shows the hidden channel but no info

**Comment by JustOptimize** [comment]
Couldn't sleep, fixed, restared discord, broken again 💀

**Comment by JustOptimize** [comment]
Discord reversed the change, bruh

**Comment by JustOptimize** [comment]
Can anyone confirm this is working again?

**Comment by JustOptimize** [comment]
If this stops working during the night, download the beta from the dev-unstable branch

**Comment by AsgoreChara666** [comment]
it fixed itself, bruh

Route isn't defined now

**Comment by Lemonsniffer9000** [comment]
> Can anyone confirm this is working again?

Yeah it's working
