### ISSUE TITLE
Server Blacklist not working.

### ISSUE THREAD

**Issue by YonDaLife** [JustOptimize/return-ShowHiddenChannels#178]
As seen in the picture, the Server Blacklist is not working/expanding.

![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/166848572/2b22878d-58be-4d0e-a43c-1000eab28a51)

**Comment by JustOptimize** [comment]
Fixed with latest version

**Comment by JustOptimize** [comment]
Compleatly fixed with 346e8f011b0929ab669e6c369586468760d28e19, thanks for reporting the issue
