### ISSUE TITLE
Hidden channel eye icon is thickk

### ISSUE THREAD

**Issue by LeonGamer1707** [JustOptimize/return-ShowHiddenChannels#180]
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/104063193/6803d6d4-7596-4baf-be0e-312c342456d3)
i don't think this is supposed to happen, is this a bug or an issue on my side?

**Comment by JustOptimize** [comment]
Can confirm, this is an issue

**Comment by JustOptimize** [comment]
Fixed in v0.4.8
