### ISSUE TITLE
ZeresPluginLibrary - An error was encountered...

### ISSUE THREAD

**Issue by imkhoa19032110** [JustOptimize/return-ShowHiddenChannels#183]
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/142767777/c844fb82-6921-47a9-a78e-3fa5ed597212)

**Comment by JustOptimize** [comment]
ZeresPL is a library that the plugin uses made by Zerebos, probably we need to wait for him to fix the issue
