### ISSUE TITLE
Role names not displayed in permissions popup

### ISSUE THREAD

**Issue by ThunderMite42** [JustOptimize/return-ShowHiddenChannels#185]
When viewing permissions for a channel, role names are completely blank. Additionally, users are only shown as an ID at first (with a random color), with the name and PFP not displaying until after clicking on the channel to view the "This is a hidden text channel" page.
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/38893728/2240a4bf-f1ad-40ec-90e2-828992de2fbd)
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/38893728/2de5e897-a517-453c-be5c-da880d1bb478)
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/38893728/8615e7e5-7c1c-4649-a09d-196738fc27aa)

**Comment by JustOptimize** [comment]
The permission popup is not part of this plugin, it is part of PermissionsViewer, there is a fork from this pull request https://github.com/rauenzi/BetterDiscordAddons/pull/759 by @ShaneMcC that fixes the roles issue.
