### ISSUE TITLE
(Bug) Crucial modules missing 

### ISSUE THREAD

**Issue by Dex679** [JustOptimize/return-ShowHiddenChannels#188]
So when i turn on the plugin it gives me this first message 
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/173215510/5b2ca239-bb55-4d5f-a722-7d525dcc6f97)

Then if i click 'start anyway' it turns on but doesnt work then below it it also gives this error 
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/173215510/0101ff84-39ef-41a8-b195-67cb3db585af)

It was working perfectly fine up until i noticed today it wasn't and i can recall it was working fine 1-2 days ago it just randomly stopped working i dont know why i havent touched my plugins so i dont know how it has just stopped working

**Comment by TheGreatTaz** [comment]
same here

**Comment by Jean4506** [comment]
Having the same issue

**Comment by ridhu-web** [comment]
same here

**Comment by coal717** [comment]
same issue

**Comment by MrLuckyGamer** [comment]
same here

**Comment by JustOptimize** [comment]
same here

**Comment by JustOptimize** [comment]
For everyone that don't know what's happening, discord updated stuff that broke the plugin, I'm fixing it

**Comment by RaGuL-26** [comment]
same :(

**Comment by JustOptimize** [comment]
Update: Did some small fixes, plugin started working with a couple of features missing (dev version)
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/54294419/7b20a2ba-4cc3-4e53-a850-6563c08ce12d)

**Comment by SomeoneWhoLike** [comment]
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/173268531/1acbcaaf-a4e2-4d5e-9ca0-53803bfaad73)
:/

**Comment by JustOptimize** [comment]
> ![image](https://private-user-images.githubusercontent.com/173268531/341073873-1acbcaaf-a4e2-4d5e-9ca0-53803bfaad73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDA0NDIsIm5iZiI6MTcxODgwMDE0MiwicGF0aCI6Ii8xNzMyNjg1MzEvMzQxMDczODczLTFhY2JjYWFmLWE0ZTItNGQ1ZS05Y2EwLTUzODAzYmZhYWQ3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQxMjI5MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjBlODQ4MzMyZGMzNmJmNjlhNTJmNjBlMWVjYWUzOTgxYzc0NjhjY2YxMWY5ZTQ2NTlkZDczZDU2ZDlhM2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SlcUcGqsuNIVxWFpfNIccVGxbjHGpNE_T-4jhDNJ0JU) :/

Thanks for adding additional information to this already estabilished issue

**Comment by jxstRoxy** [comment]
Hi I have the same error unfortunately :(

**Comment by KraZ5M** [comment]
![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/115189405/f62a11c6-c6be-4591-9996-664d7093aa86)

**Comment by MikeApfelbaum** [comment]
Can you fix the shit already? What's taking so long?

**Comment by FilipeGiesta** [comment]
Imagine being rude to someone that's actually hard working to provide a great working plugin FOR FREE.

Take your time mate @JustOptimize !

**Comment by JustOptimize** [comment]
> Can you fix the shit already? What's taking so long?

Like...I'm at WORK?!

**Comment by CookieProgrammer93** [comment]
> Can you fix the shit already? What's taking so long?

Dude chill he'll fix it. JustOptimize bro the latest plugin temporary one you added that is also not working aint showing anything jst says error encountered

**Comment by JustOptimize** [comment]
> Dude chill he'll fix it. JustOptimize bro the latest plugin temporary one you added that is also not working aint showing anything jst says error encountered

Try this (hidden channel icon and page are missing)
https://github.com/JustOptimize/return-ShowHiddenChannels/blob/dev-unstable/ShowHiddenChannels.plugin.js

**Comment by Petertnr** [comment]
It's the same problem. Doesn't working.

**Comment by ajxiicek** [comment]
> > Dude chill he'll fix it. JustOptimize bro the latest plugin temporary one you added that is also not working aint showing anything jst says error encountered
> 
> Try this (hidden channel icon and page are missing) https://github.com/JustOptimize/return-ShowHiddenChannels/blob/dev-unstable/ShowHiddenChannels.plugin.js

![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/173286998/2f4bb170-710c-4f35-9c26-1e2816d2f873)

**Comment by JustOptimize** [comment]
Idk, wait for an update I guess

**Comment by IamAnimy** [comment]
![Screenshot 2024-06-20 015551](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/173302512/77fc97fb-b005-4baf-a9aa-f3caabbc0c1a)
Maybe this will help you

**Comment by rom4ster** [comment]
> Can you fix the shit already? What's taking so long?

If you want to be up to date with the latest and greatest, why dont u go and use the dev branch instead of whining like a bitch.

**Comment by alangrahnt** [comment]
люди а кто знает когда примерно оно заработает ?

**Comment by JustOptimize** [comment]
> люди а кто знает когда примерно оно заработает ?

Idk, maybe a couple of hours, maybe a day

**Comment by alangrahnt** [comment]
но к завтрашнему дню оно  оно будет хотя бы работать ?

**Comment by Dex679** [comment]
@JustOptimize take your time people are bitch per usual LMAOO

**Comment by zofiell** [comment]
hola yo tb tengo ese mismo error

**Comment by ManchiSoul** [comment]
> > Dude chill he'll fix it. JustOptimize bro the latest plugin temporary one you added that is also not working aint showing anything jst says error encountered
> 
> Try this (hidden channel icon and page are missing) https://github.com/JustOptimize/return-ShowHiddenChannels/blob/dev-unstable/ShowHiddenChannels.plugin.js

Ty so much i appreciate the work and effort you do to keep this plugin alive. i salute you sir. and i would like to say this plugin u just post the link works PERFECTLY FINE for me

Again.. much appreciate it to you

**Comment by alangrahnt** [comment]
у меня не работает просто не показываются каналы

**Comment by Ashio-Kun** [comment]
Hi, so I tried tu use the dev-unstable build of SHC but it doesn't show hidden channels, however the plugin launches perfectly fine

**Comment by alangrahnt** [comment]
у меня тоже самое

**Comment by zofiell** [comment]
solo queda esperar

**Comment by svuddi** [comment]
For me, I've installed the newest version you've attached here previously, it's not showing me the same error message, but it's not working as well for me I dunno why, just leaving this as a feedback, GL.

**Comment by Dex679** [comment]
> Hi, so I tried tu use the dev-unstable build of SHC but it doesn't show hidden channels, however the plugin launches perfectly fine

exact same for me plugin launched fine but didnt work didnt give me no missing module error or anything this time

**Comment by xrvnxxl** [comment]
If it suddenly helps: There is a Bluecord application on Android, all hidden channels are shown there, nothing is broken. If it has source code (I don't know for sure) then maybe this information will help you fix the plugin? @JustOptimize

**Comment by JustOptimize** [comment]
> If it suddenly helps: There is a Bluecord application on Android, all hidden channels are shown there, nothing is broken. If it has source code (I don't know for sure) then maybe this information will help you fix the plugin? @JustOptimize

Unfortunatly Android discord is compleatly a different thing than Desktop one.
The plugin is semi working anyways, some modules are wrong so I'm checking one by one if they are the correct one.
I'm at a stage where it is only missing the hidden channel page

**Comment by xrvnxxl** [comment]
> > Если вдруг поможет: Есть приложение Bluecord на Андроиде, там показаны все скрытые каналы, ничего не сломано. Если у него есть исходный код (точно не знаю), то, возможно, эта информация поможет вам починить плагин?@JustOptimize
> 
> К сожалению, Android Discord — это совсем другое дело, чем настольный компьютер. В любом случае плагин частично работает, некоторые модули неправильные, поэтому я проверяю один за другим, правильные ли они. Я нахожусь на этапе, когда отсутствует только страница скрытого канала.

Kk, thanks for answer. Good luck :)

**Comment by JustOptimize** [comment]
Fixed with v0.5.0

**Comment by smallwu587** [comment]
thx

**Comment by 6DagDaMor6** [comment]
Thank you for your efforts
