### ISSUE TITLE
Broken Modules

### ISSUE THREAD

**Issue by KraZ5M** [JustOptimize/return-ShowHiddenChannels#190]
Went to load up this morning and it the plugin came up with '(SHC) Broken Modules', and can't see to fix it. 

Can someone help me?

![image](https://github.com/JustOptimize/return-ShowHiddenChannels/assets/115189405/769bbb99-5aa3-4e72-82b4-bd29392fe4b1)

**Comment by JustOptimize** [comment]
Dupe of #188
