### ISSUE TITLE
(BUG) Error displaying hidden channels after reload.

### ISSUE THREAD

**Issue by NotCapengeR** [JustOptimize/return-ShowHiddenChannels#25]
Reproduce steps:
1) Select Discord server with hidden channels.
2) Press reload (Ctrl + R)).
3) Now you can see on the selected server all hidden channels except selected aren't displaying

Proof (can't attach video, 'cuz too big size :C): https://www.youtube.com/watch?v=8apDef9Pfi0

**Comment by JustOptimize** [comment]
**Update**

With the new updates the situation has improved, now you can click 2 times on the category the channel is in and it will display correctly.
Or if it is a large guild scroll up and down to fix it.
