### ISSUE TITLE
(Enhancement) Padlock Icon

### ISSUE THREAD

**Issue by black-trush** [JustOptimize/return-ShowHiddenChannels#26]
In the current version there is no visual distinction.
As with the original, unpermission channels should be distinguished by a padlock icon.

**Comment by JustOptimize** [comment]
![image](https://user-images.githubusercontent.com/54294419/196052345-7b8ca7fc-c914-4794-ae95-991c29303f90.png)
I already specified in the readme that this is being worked on

**Comment by vileelf** [comment]
`var channelChanging = false;
         Patcher.after(ChannelStore, "getChannel", (thisObject, methodArguments, returnValue) => {
           if (channelChanging == false) {
             channelChanging = true;
             if (returnValue?.isHidden?.() == true 
                && returnValue?.name 
                && !returnValue.name.startsWith(" 🔒 ")) {
                  returnValue.name = " 🔒 " + returnValue.name;
             }
             channelChanging = false;
           }
         });` heres a quick fix for your lock code. it should work fine as long as theres no multithreading.

**Comment by JustOptimize** [comment]
Oh, thanks
