### ISSUE TITLE
(Enhancement) Channel permissions submenu

### ISSUE THREAD

**Issue by black-trush** [JustOptimize/return-ShowHiddenChannels#27]
restore this functionality that existed in the original.

**Comment by JustOptimize** [comment]
![image](https://user-images.githubusercontent.com/54294419/196716252-f0a3de92-fa8d-481d-835a-8d9ad2c08b5c.png)

**Comment by JustOptimize** [comment]
You can use [this](https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/PermissionsViewer) plugin to see the channel access.

**Comment by ImSnipper** [comment]
![image](https://user-images.githubusercontent.com/26206574/204067861-ae08dbc7-dd1f-4a3b-bdd3-15f8d6a27cc7.png)

The ability to see the channel access does not appear to be working. 

I should only have to right click on the channel, and there should be a "Channel Access" option, correct? I am on the latest version of the plugin. 

Any idea? Thanks!

**Comment by JustOptimize** [comment]
Have you downloaded the permissionviewer plugin?
