### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by MatchesxMalone** [JustOptimize/return-ShowHiddenChannels#28]
Not sure why as I'm following the instructions to the best of my knowledge but this never seems to want to load on my end. It'll say it's been loaded but nothing changes. I'll restart Discord and nothing changes. Should it be working properly now after the update or is it still being worked on?

**Comment by JustOptimize** [comment]
It should work properly, are you sure this isn't #25?

**Comment by MatchesxMalone** [comment]
> It should work properly, are you sure this isn't #25?

I'll try it again just to be sure.

**Comment by MatchesxMalone** [comment]
> It should work properly, are you sure this isn't #25?

Actually, I watched the video on that one. It's not that at all. The plugin just genuinely doesn't load for me. It says it's loaded and that it should be working but there's zero change.

**Comment by MatchesxMalone** [comment]
Update: Not sure what I did different, but it is indeed now working.
