### ISSUE TITLE
can you do something?

### ISSUE THREAD

**Issue by speedlorenzo12** [JustOptimize/return-ShowHiddenChannels#32]
can you make sure you don't get into locked channels and do the effect as if a channel doesn't load (I mean when you click a channel it's like when you click a background with no properties) when you click one?

**Comment by JustOptimize** [comment]
It's not a bug it's literally a feature

**Comment by XHesaX** [comment]
> It's not a bug it's literally a feature In this way you can read the channel topic (description)

good
