### ISSUE TITLE
(Enhancement) Hidden channel page

### ISSUE THREAD

**Issue by Azurz** [JustOptimize/return-ShowHiddenChannels#35]
Hello,
Do you think it's possible to do this?

![182038484-325a5193-3bca-45dd-8091-3abe03f543b8](https://user-images.githubusercontent.com/35930914/196167378-be25b73e-839e-4e4e-8399-b0110ea09ca9.png)

**Comment by JustOptimize** [comment]
Check [this](https://github.com/JustOptimize/return-ShowHiddenChannels/tree/dev-unstable) branch,
test it,
if you find bugs, report them here.

If no bugs are found expect a merge in a few days

**Comment by Azurz** [comment]
Okay, I'll test this.
