### ISSUE TITLE
(DevHelp) ChannelUtil, Voice and ChannelItem

### ISSUE THREAD

**Issue by xPumaa** [JustOptimize/return-ShowHiddenChannels#36]
Are these the ones that are missing?

```js
const ChannelUtil = WebpackModules.getByProps("selectChannel", "selectPrivateChannel");
const VoiceUser = WebpackModules.getByPrototypes("renderPrioritySpeaker", "renderIcons", "renderAvatar")
const VoiceUsers = WebpackModules.getByString("hidePreview", "previewIsOpen", "previewUserIdAfterDelay");
const ChannelItem = WebpackModules.getByString("canHaveDot", "unreadRelevant", "UNREAD_HIGHLIGHT")
```

**Comment by JustOptimize** [comment]
Yep, thank you ❤

**Comment by JustOptimize** [comment]
Can you take a look at [this](https://github.com/JustOptimize/return-ShowHiddenChannels/tree/dev-unstable)?
Do you know how to fix anything?

**Comment by xPumaa** [comment]
unfortunately not

**Comment by xPumaa** [comment]
btw. i got the old version from devilbro working again.

**Comment by JustOptimize** [comment]
I was thinking about it, but then I thought I should stop relying on Devil's crappy library.

**Comment by xPumaa** [comment]
yes sure, but now I can tell you that you can't patch ChannelItem like you did.
ChannelItem is pure js and not a webpack, if I understand correctly.
So you have to do it like [this](https://github.com/mwittrien/BetterDiscordAddons/blob/5f53f2c0a28141e3d45f44bbe314d421d32164e4/Library/0BDFDB.plugin.js#L2149)
