### ISSUE TITLE
The unread icon does not disappear.

### ISSUE THREAD

**Issue by Tomo-Tg** [JustOptimize/return-ShowHiddenChannels#38]
Once you try to open a hidden channel, the unread mark will not disappear from the server icon.
If I try to right click on the server and press the button to mark it as read, it is blacked out and I cannot press it.
The only way to get rid of the unread mark is to restart the discord.

**Comment by xPumaa** [comment]
![image](https://user-images.githubusercontent.com/35280763/196565242-fbb70d24-6c29-469a-86bc-397808ab362b.png)

**Comment by Tomo-Tg** [comment]
I did not read it, sorry.
