### ISSUE TITLE
Unread messages in hidden channels

### ISSUE THREAD

**Issue by SKProCH** [JustOptimize/return-ShowHiddenChannels#39]
When i install the plugin and navigate to large server with many hidden channels, i get dot, indicating what i have unread messages, in server list:  
![image](https://user-images.githubusercontent.com/29896317/196788887-2e8ccc6e-2df7-4361-bf67-50b58d27d824.png)
I can't mark it as read and it stays here forever (apparently).

**Comment by xPumaa** [comment]
https://github.com/JustOptimize/return-ShowHiddenChannels/issues/38#issuecomment-1283144029

**Comment by JustOptimize** [comment]
Yep duplicate
