### ISSUE TITLE
[Suggestion] Cooperative request

### ISSUE THREAD

**Issue by phoriah** [JustOptimize/return-ShowHiddenChannels#4]
There is currently another group of people trying to fix this big issue.
[here](https://github.com/Saalvage/BetterDiscordAddons)
They also have their own Discord and Subreddit dedicated to all of this (you can find it on opened issue there)
All I'm saying is if you could potentially team up with them and unite your efforts I think that'd be great.
If more similar projects arise I will try to notify you and them.
Just a suggestion!
Thanks, P.

**Comment by JustOptimize** [comment]
Hi, I've already seen the project, I will happily collaborate with the developers 👍🏻

**Comment by JustOptimize** [comment]
The linked repo got archived
