### ISSUE TITLE
VoiceActivity compability

### ISSUE THREAD

**Issue by SKProCH** [JustOptimize/return-ShowHiddenChannels#40]
Seems like original ShowHiddenChannels works perfectly with [VoiceActivities](https://github.com/Neodymium7/BetterDiscordStuff/tree/main/VoiceActivity) plugin. And currently this plugin does not:  
![image](https://user-images.githubusercontent.com/29896317/196790596-04bebffe-fec5-43b7-aac7-680fb0f9f654.png)  
For example, i can see, what person streaming, but i doesn't see voice activity icon.  
It would be great if this were ever implemented.

**Comment by JustOptimize** [comment]
See #14
