### ISSUE TITLE
Enhancement- Add a update Log in Readme

### ISSUE THREAD

**Issue by FASTANDEXTREME** [JustOptimize/return-ShowHiddenChannels#49]
Please add what things you updated in code in readme so we know which new feature is available or what issues are being fixed.

**Comment by JustOptimize** [comment]
New avaiable features/fixes are shown every update on your discord client via the changelog popup.
![image](https://user-images.githubusercontent.com/54294419/197592223-aae2dd0c-29de-4d60-966e-a7d56857bb4a.png)

For the `what issues are being fixed.` part you can now check the readme and the github issues page
![image](https://user-images.githubusercontent.com/54294419/197592536-044c2507-438d-4852-8a41-c9e3c7e1872e.png)
