### ISSUE TITLE
Always have to reload (Without-Library version).

### ISSUE THREAD

**Issue by Zadowcloud** [JustOptimize/return-ShowHiddenChannels#5]
If I install this plugin I always have to reload it in settings for it to work. Any help is appreciated :)

**Comment by JustOptimize** [comment]
What platform are you using Discord on?
What version of discord do you have?
What is the version of the plugin you are using?
Do you see an error in the Discord console?

**Comment by Zadowcloud** [comment]
Platform: M1 Mac
Version: Stable 146284 (57b3d6d) BetterDiscord 1.6.3
Pluginversion: 4.0.2
Not sure where to find the console

**Comment by Zadowcloud** [comment]
At the moment it does not. I'll make a screenrecording really quick

**Comment by Zadowcloud** [comment]
https://www.mediafire.com/file/74ncxdwxfp285cm/Bildschirmaufnahme+2022-09-09+um+20.12.29.mov/file

File was too big to upload it here sadly.

**Comment by JustOptimize** [comment]
Can you screen record the console content? to open it it's ctrl+shift+i

**Comment by JustOptimize** [comment]
Ok, i was able to replicate the issue, I will keep you updated

**Comment by Zadowcloud** [comment]
Awesome! I can't open the console. Tried enabling it in settings.json but it already was. Turns out it doesn't exist on Stable anymore. Maybe with a plugin tho...

**Comment by JustOptimize** [comment]
Lol, have you tried any other plugins? I can't figure it out, just pressing ctrl + r on discord (essentially restarting it) fixes the 
problem, wtf!?

**Comment by Zadowcloud** [comment]
Tried it too, Ctrl+R fixes it for me too. Weird bug...

**Comment by NotCapengeR** [comment]
The ShowHiddenChannels plugin is no longer supported so expect new similar bugs that are unlikely to ever be fixed. Although there may be a developer who will fix everything

**Comment by JustOptimize** [comment]
> The ShowHiddenChannels plugin is no longer supported so expect new similar bugs that are unlikely to ever be fixed. Although there may be a developer who will fix everything

That's why we have a github repo; me and other developers want to fix these bugs

**Comment by NotCapengeR** [comment]
> EDIT: Don't you have a fork of the plugin too?
Yes. And I have the same issue on my version. 

> That's why we have a github repo; me and other developers want to fix these bugs
Are you a BetterDiscord plugin developer? :) If not, I think it could be difficult to fix this bug

**Comment by JustOptimize** [comment]
> Are you a BetterDiscord plugin developer? If not, I think it could be difficult to fix this bug ;)

No, but I can try at least to feagure out what's happening like the fact that `processChannelList()` doesn't get called if discord starts normally.

**Comment by NotCapengeR** [comment]
> No, but I can try at least to figure out what's happening like the fact that processChannelList() doesn't get called if discord starts normally.

Maybe it's just a library bug. Maybe not... But without plugin developer help supporting of this plugin is impossible I think. But let us know the solution if you find it

**Comment by JustOptimize** [comment]
@Zadowcloud as a temporary fix i made the With-Library version avaiable again [here](https://github.com/JustOptimize/return-ShowHiddenChannels/tree/With-Library), can you tell me if it fixes your problem?

To use it make sure to remove the  returnShowHiddenChannels plugin

**Comment by Staticdevvv** [comment]
it wont work for me

**Comment by JustOptimize** [comment]
> it wont work for me

Can you be more specific?

**Comment by binnesman** [comment]
I can't seem to get either version to work for me at all, with or without library, and reloading the plugin, restarting discord. It was working for me the past days. Any advice, how can I help you?

**Comment by Zadowcloud** [comment]
> fix i made the With-Library version avaiab

This one works. I just tried it. Thank you :)

**Comment by Nexinity7** [comment]
+1 here! 
Ptb 146518 (20432be)
BetterDiscord 1.6.3
Host 1.0.1018 
Windows 10 64-Bit (10.0.19044)

**Comment by rom4ster** [comment]
> > EDIT: Don't you have a fork of the plugin too?
> 
> Yes. And I have the same issue on my version.
> 
> > That's why we have a github repo; me and other developers want to fix these bugs
> 
> Are you a BetterDiscord plugin developer? If not, I think it could be difficult to fix this bug ;)

He managed to seperate the library from the plugin so that alone is hard given how hidden this feature is to work with thats a plus. 


I have the same issue, have you tried issuing a delay before running the offending function?

**Comment by JustOptimize** [comment]
The issue is that processChannelList isn't the same of processChannels and the last one got removed from the official library.
This is why `a rewrite of the plugin` /  `a plugin to modify the library data` / `a custom library` is needed.
At the moment if you don't want an extra library you could try [this](https://github.com/Tharki-God/BetterDiscordPlugins/blob/master/ShowHiddenChannels.plugin.js).
It's a rewritten version of Devil's plugin with extra features and doesn't use 0BDFDB and instead uses 0PluginLibrary (Made by Tharki-God (a really good dev))
