### ISSUE TITLE
(BUG) Old emoji icon is stuck

### ISSUE THREAD

**Issue by Soulivan71** [JustOptimize/return-ShowHiddenChannels#53]
Can we remove lock yellow icon ? and just have the lock grey icon on right ?

**Comment by JustOptimize** [comment]
You need to restart discord after the update

**Comment by Soulivan71** [comment]
Nothing change after restart

**Comment by Soulivan71** [comment]
![6FE44F2B-4BE0-4840-938A-1F2D9ADF05D8](https://user-images.githubusercontent.com/36502190/198530003-c7f2b2c8-5556-4f62-be72-d43d6e8dd087.png)

**Comment by JustOptimize** [comment]
Same as #50, gonna close that and move the issue here

**Comment by soudblox** [comment]
I fixed this issue by disabling the lock icon in settings, then re-enabling it.

**Comment by Soulivan71** [comment]
> I fixed this issue by disabling the lock icon in settings, then re-enabling it.

I already tried this and don't work for me

**Comment by Soulivan71** [comment]
I alredy try this all options 400times fr

**Comment by JustOptimize** [comment]
Oh wait, i forgot to tell you to download (this)[https://raw.githubusercontent.com/JustOptimize/return-ShowHiddenChannels/dev-unstable/ShowHiddenChannels.plugin.js], i'm dumb

**Comment by Soulivan71** [comment]
Nothing change

**Comment by JustOptimize** [comment]
Are you up for a discord call?

**Comment by Soulivan71** [comment]
Now I cant btw :(

**Comment by JustOptimize** [comment]
Okay, this problem only occurs on Windows...wtf

**Comment by Soulivan71** [comment]
Ur using macos ?

**Comment by JustOptimize** [comment]
> Ur using macos ?

Eww no, linux is the way my guy

**Comment by Soulivan71** [comment]
Ok

**Comment by JustOptimize** [comment]
The solution is to clean `CacheStoreLazy` and `CacheStoreChannelsLazy` from the localstorage but plugins can't access it

**Comment by Soulivan71** [comment]
This clear nothing more?

**Comment by JustOptimize** [comment]
Yep, restart discord and you're good to go

**Comment by Soulivan71** [comment]
Appdata roaming ?

**Comment by JustOptimize** [comment]
This is not a fix, It's just a temp solution, a solution will be pushed in a few days

**Comment by JustOptimize** [comment]
Completly removed the lock icons with the last update indeed fixing this issue
