### ISSUE TITLE
2 lock icons on voice channels

### ISSUE THREAD

**Issue by Shayush04** [JustOptimize/return-ShowHiddenChannels#55]
![image](https://user-images.githubusercontent.com/5853511/198527062-1ab5f73e-d9b0-492d-8932-c91fb3bb35a0.png)

**Comment by JustOptimize** [comment]
The lock on the left is the voice channel lock, it means you can't access the channel.
You could still see a channel with that lock with no plugin enabled

**Comment by Shayush04** [comment]
> The lock on the left is the voice channel lock, it means you can't access the channel. You could still see a channel with that lock with no plugin enabled

these channels have denied permissions for show channel, that lock is related to the plugin
