### ISSUE TITLE
(BUG) Changing the settings causes the plugin to stop working.

### ISSUE THREAD

**Issue by Randomdudeforsomereason** [JustOptimize/return-ShowHiddenChannels#61]
https://gyazo.com/122a6e972db447c5a72926170bfcdd49
I decided to check out the Settings and try to Enable Debug Mode and the Hidden Channels disappears
I disable it and it still stay the same even restarting discord doesn't work

**Comment by JustOptimize** [comment]
Can you be a little more specific?
On what OS are you?
