### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by martinclub** [JustOptimize/return-ShowHiddenChannels#62]
Hello first of all thanks for your plugin, I am here to report the bug I have with this plugin, when I activate my Discord Crashes
![image](https://user-images.githubusercontent.com/1719365/200629403-eccf25db-fedf-4eb0-b919-f2cfbf530d1b.png)
If u need something from me don't hesitate to ask me!

Best Regards,
Marty

**Comment by JustOptimize** [comment]
Hi, was having the same issue but after disabling some plugins it stopped crashing (Mine still works)

**Comment by JustOptimize** [comment]
I disabled FakeDeafen, MentionCacheFix and PersitSettings to stop it from crashing.

**Comment by martinclub** [comment]
damm this settings in the plugin just fixed my problem
![image](https://user-images.githubusercontent.com/1719365/200733155-07ccca71-dbe6-4bb3-be47-cf85249f0ab4.png)

Thanks anyways JustOptimize
