### ISSUE TITLE
(Enhancement) Remove the ability to go to the chat of inaccessible channels or make this feature customizable

### ISSUE THREAD

**Issue by BEBRONYH** [JustOptimize/return-ShowHiddenChannels#63]
Remove the ability to go to the chat of inaccessible channels or make this feature customizable, as it is sometimes very inconvenient and interferes

**Comment by JustOptimize** [comment]
How could this "interfere" and be "inconvenient", please specify

**Comment by Luigi534** [comment]
I'm not the person who wrote this, but sometimes on the new discord server it puts me in a channel that I don't usually have access to (most of the time it's the verification channel), so I don't see anyone connecting and I have to manually go to a channel that I have access to. The same thing when you have had access to a voice that normally you don't have access, if you don't click on a normal channel after the voice session you will have to manually click on a channel that the person has access to.

Maybe put an option like he said, customizable if the person really doesn't want to go back to a channel that has access every time. but to be honest it's not a priority for me, I just have to make 2 clicks and that's it

**Comment by JustOptimize** [comment]
Discord server invites are linked to a channel.
> If it is done by clicking on the guild, it will be the first channel that the user who made the invitation is able to see.

Discord will redirect you to that channel, visible or not, so having the ability to click on the channel doesn't matter. (This happens without the plugin too)
But thanks for the clarification <3
