### ISSUE TITLE
ShowHiddenChannels

### ISSUE THREAD

**Issue by Soulivan71** [JustOptimize/return-ShowHiddenChannels#65]
Im still having the channels like is unread when new msg are posted (on hidden channel)
Even if I have the snd settings up
PTB Lastv
Canary Lastv
Stable Lastv

**Comment by Soulivan71** [comment]
I found a fix bymyself

**Comment by JustOptimize** [comment]
> I found a fix bymyself

What was the problem anyway? How you fixed it?

**Comment by Soulivan71** [comment]
I see the hidenn channels has unread

**Comment by Soulivan71** [comment]
![image](https://user-images.githubusercontent.com/36502190/201744628-89225c75-9653-46f9-80ed-bf5fe43a38a4.png)

**Comment by JustOptimize** [comment]
And how you fixed it?
