### ISSUE TITLE
(Enhancement) Turn off viewing hidden channels on a per-server basis

### ISSUE THREAD

**Issue by VadimGubin98** [JustOptimize/return-ShowHiddenChannels#66]
Previously, in older versions of the plugin, it was possible to display all hidden channels in a separate "hidden" category from the bottom, is it possible to implement this?

**Comment by JustOptimize** [comment]
Probably, thanks for the suggestion

**Comment by PikachuGabe** [comment]
Or,if not this,the ability to turn off viewing hidden channels on a per-server basis like in the original plugin before it got banned.

**Comment by JustOptimize** [comment]
> Or,if not this,the ability to turn off viewing hidden channels on a per-server basis like in the original plugin before it got banned.

Will be in the next release 😉
