### ISSUE TITLE
[Bug] Hidden channel see like normal 

### ISSUE THREAD

**Issue by Soulivan71** [JustOptimize/return-ShowHiddenChannels#67]
![image](https://user-images.githubusercontent.com/36502190/202050491-6f20b382-80bb-4670-9d1e-9c7435d25e90.png)
![image](https://user-images.githubusercontent.com/36502190/202050546-9485fad3-d092-4843-83c5-7f729654b1da.png)
![image](https://user-images.githubusercontent.com/36502190/202050585-b838a11f-db4c-430f-a8f6-680512b5e21c.png)
Ptb 158686 (01fe583) Host 1.0.1020 (26825) Windows 10 64-Bit (10.0.19045)

**Comment by Soulivan71** [comment]
Its only on one serv explication ? :x

**Comment by JustOptimize** [comment]
What version of ShowHiddenChannels are you using?
Have you tried redownloading the plugin?

**Comment by Soulivan71** [comment]
0.0.8

**Comment by JustOptimize** [comment]
Have you tried reinstalling the plugin?

**Comment by Soulivan71** [comment]
Yes not fixing

**Comment by Soulivan71** [comment]
![image](https://user-images.githubusercontent.com/36502190/202803152-e34564eb-42fe-4802-9066-fe8a7c9ec635.png)
If he can helped u

**Comment by JustOptimize** [comment]
Oh the issue are these channels
![image](https://user-images.githubusercontent.com/54294419/202808930-258727c2-2a2f-4127-bba7-d3d53e473991.png)

Can you invite me into a discord server with that?
Or at least, can you message me on discord (Oggetto#7270) to get this fixed?

**Comment by JustOptimize** [comment]
[ShowHiddenChannels.plugin.zip](https://github.com/JustOptimize/return-ShowHiddenChannels/files/10045112/ShowHiddenChannels.plugin.zip)
Try this and tell me if it fixes your problem

**Comment by Soulivan71** [comment]
For the top of topic nothing change,
And for 2nd I can't say now cause its happened due to a big waves of message on public server for example.
So I wll take back in few hours to say if ur fix do smthg

**Comment by Soulivan71** [comment]
> [ShowHiddenChannels.plugin.zip](https://github.com/JustOptimize/return-ShowHiddenChannels/files/10045112/ShowHiddenChannels.plugin.zip) Try this and tell me if it fixes your problem

Seems to work fine, thx to ur reactivity

**Comment by Soulivan71** [comment]
Nothing change finally

**Comment by Soulivan71** [comment]
Not fix

**Comment by JustOptimize** [comment]
Could you record the screen by showing the settings, logs (console), and the bug itself?

**Comment by Soulivan71** [comment]
Do u have a recording name app ?

**Comment by Soulivan71** [comment]
Since last update now I crash without any error cause my app is crashing and restarting so I cannot see the console log 
(crash appear only when ur pl is enable)

**Comment by JustOptimize** [comment]
> Since last update now I crash without any error cause my app is crashing and restarting so I cannot see the console log (crash appear only when ur pl is enable)

That's why I need to see what's happening in the console.


Btw you have "Stop marking hidden channels as read" enabled so It's normal that you see the unread notification
In the next release the lock icon mechanism will be improved and use less resources so stay tuned 😉

**Comment by Soulivan71** [comment]
Ok but where I can find logs if my app crash...

**Comment by Soulivan71** [comment]
Since I remove "Stop marking hidden channels as read" seems to not crash anymore

**Comment by JustOptimize** [comment]
> Since I remove "Stop marking hidden channels as read" seems to not crash anymore

Keep that disabled, I was thinking to remove it anyway in the future.
Why you had it enabled? Was it useful? If so, how?

**Comment by Soulivan71** [comment]
Cause I miss understand, yes I don't want to, thats the thing I say early but U didn't notice me so thx !
Little suggestion : with the old pl we have a setting where we can enabled/disabled the showhiddenchannels for certain servers can u do it in future ?
(Its like blacklist servers)

**Comment by JustOptimize** [comment]
Yes it will be added next release (0.1.0)

**Comment by Soulivan71** [comment]
Okay
