### ISSUE TITLE
[BUG] SHC v0.0.8 - Crashing discord when "View Server As Role" on very large servers.

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [JustOptimize/return-ShowHiddenChannels#68]
@JustOptimize 
Screens:
<img width="1646" alt="Screen Shot 2022-11-19 at 11 35 41 am" src="https://user-images.githubusercontent.com/2242880/202824712-c0bc5bb2-813d-4061-b2aa-df53155fc558.png">
<img width="1166" alt="Screen Shot 2022-11-19 at 11 35 30 am" src="https://user-images.githubusercontent.com/2242880/202824727-09712139-7cf3-4680-b7c0-d15ab822a8ef.png">
Logs:
[debug.log](https://github.com/JustOptimize/return-ShowHiddenChannels/files/10045645/debug.log)
[SHC.log](https://github.com/JustOptimize/return-ShowHiddenChannels/files/10045646/SHC.log)

[Video](https://replay.dropbox.com/share/tE4hgWQNZK72PqW1)

So when going to "View Server As Role" with this plugin on it crashes my discord, this does not happen on small servers.
you need to be in a big server with like 40-80+ roles & and 30-40+ channels.

this a problem for me as server admin as I use this feature from discord to check for issues.

```text
Stable 159692 (79ae406) Host 0.0.269 | OpenAsar 7a04cb5 OS X 10.15.7 (20.6.0)
```

**Comment by JustOptimize** [comment]
Check the dev-unstable branch, I changed the way I handled the hidden channels.
Can you tell me if the issue persists?

**Comment by XxUnkn0wnxX** [comment]
still crashing sadly 
<img width="2161" alt="Screen Shot 2022-11-21 at 2 43 17 am" src="https://user-images.githubusercontent.com/2242880/202911497-44fcc6cb-53a0-4a9b-ab11-68f7ee1212bf.png">
[SHC_console.log](https://github.com/JustOptimize/return-ShowHiddenChannels/files/10050087/SHC_console.log)

**Comment by JustOptimize** [comment]
> still crashing sadly <img alt="Screen Shot 2022-11-21 at 2 43 17 am" width="2000" src="https://user-images.githubusercontent.com/2242880/202911497-44fcc6cb-53a0-4a9b-ab11-68f7ee1212bf.png"> [SHC_console.log](https://github.com/JustOptimize/return-ShowHiddenChannels/files/10050087/SHC_console.log)

Fixed this error with last update (still in the dev-unstable branch).
Does the other error still persist?

**Comment by XxUnkn0wnxX** [comment]
yep all good commit f5165028e29a819aec9038e5c7bc084f75f944ca fixed it..

**Comment by JustOptimize** [comment]
Keep this open until the release to avoid duplicates
