### ISSUE TITLE
(Problem) Not showing up in plugins 

### ISSUE THREAD

**Issue by Pickymarker** [JustOptimize/return-ShowHiddenChannels#69]
not showing up in plugins or me

**Comment by flyingwolf79** [comment]
Is the file in your plugins folder? Have you restarted Discord?

**Comment by Pickymarker** [comment]
yes to both

**Comment by JustOptimize** [comment]
Are you sure the plugin is named correctly?
(Ending with .plugin.js)

**Comment by JustOptimize** [comment]
Helloooo? Are you still there? Any updates?

**Comment by Pickymarker** [comment]
its fixed
