### ISSUE TITLE
hidden text channels only ?

### ISSUE THREAD

**Issue by lilloushx** [JustOptimize/return-ShowHiddenChannels#7]
it only shows hidden text channels not the vocal ones?
PS: thank you so much for making this work again

**Comment by NotCapengeR** [comment]
> it only shows hidden text channels not the vocal ones? 

False 
![изображение](https://user-images.githubusercontent.com/90960831/189492363-4b2b89d0-f30e-42e7-96fa-66e6014f8ffe.png)

**Comment by lilloushx** [comment]
It's only showing the hidden text chats for me

**Comment by lilloushx** [comment]
Nvm it's working finally thank you !!
