### ISSUE TITLE
Repetitive "Channel is hidden, not fetching messages"

### ISSUE THREAD

**Issue by eightyy8** [JustOptimize/return-ShowHiddenChannels#70]
Each visit your cursor takes above any hidden channel replies with a "Channel is hidden, not fetching messages"
So scrolling down an alley of hidden channels will overflow you.

See gif below, or click [here](https://i.imgur.com/CPxhxcn.gif) if it isn't loading.
![](https://i.imgur.com/CPxhxcn.gif)

(v0.0.8, Running Windows 10)

**Comment by JustOptimize** [comment]
This is not an issue since it shows correctly that the channel you clicked is an hidden channel.
It will be fixed anyway in the 0.1.0 release since I'll bring back the "Channel is hidden" page see #35 and there won't be any message popping up

**Comment by eightyy8** [comment]
> It will be fixed anyway in the 0.1.0 release since I'll bring back the "Channel is hidden" page

Nice! that's good to hear.

> it shows correctly that the channel you clicked is an hidden channel.

That's the problem, I never clicked on any; I only hovered my cursor over it.

**Comment by eightyy8** [comment]
If I actually do click on a channel, it will show me the default channel message loading, but obviously never load anything.

**Comment by eightyy8** [comment]
So maybe before you finish the channel hidden page, fix this as part v0.0.9

**Comment by JustOptimize** [comment]
> That's the problem, I never clicked on any; I only hovered my cursor over it.
Ohh

> So maybe before you finish the channel hidden page, fix this as part v0.0.9
It's already been finished for a couple of days, I'm waiting for some people to use it to find bugs.
Today or tomorrow it will probably be merged since all the bugs reported have been fixed
