### ISSUE TITLE
(Bug) - Hide Locked Channels context menu appears twice

### ISSUE THREAD

**Issue by Soulivan71** [JustOptimize/return-ShowHiddenChannels#75]
With last version :
![image](https://user-images.githubusercontent.com/36502190/203654895-79fcf3db-ab03-4093-97eb-1673f74f9e17.png)

**Comment by Soulivan71** [comment]
Fixed with ur last version

**Comment by JustOptimize** [comment]
But I havent changed anything regarding this.
The solution was just to restart the plugin/discord I guess

**Comment by Soulivan71** [comment]
Hmm no cause I tried
