### ISSUE TITLE
(enhancement) make it so forum channels show the guidelines, tags, and if having a tag is required to post 

### ISSUE THREAD

**Issue by J-URL** [JustOptimize/return-ShowHiddenChannels#76]

**Comment by JustOptimize** [comment]
![image](https://user-images.githubusercontent.com/54294419/204019147-52e4a7ca-9103-4a73-a60d-f6f902b374c8.png)

Any advice about the design?

**Comment by JustOptimize** [comment]
>having a tag is required to post

I think it's useless since you can't post anyway 🤷🏻‍♂️, if you anyone reading this want that feature tell me why with a comment
