### ISSUE TITLE
(Enhancement) Show member-specific permissions?

### ISSUE THREAD

**Issue by CandleMoth** [JustOptimize/return-ShowHiddenChannels#88]
Before the plugin was taken down, several versions showed member-specific permissions alongside the role-based ones you can already see in this version (iirc in the latest working update they weren't shown anymore, but it seemed to alternate, being intermittently fixed/patched back in). Is that information still accessible, and if so, are there any plans to add it?
Unfortunately, I have no record of what this looked like when it was working (I avoided taking screenshots that showed BetterDiscord/related UI) if that would be any help, but they were just listed alongside the role permissions, so I assumed they were retrieved similarly.

**Comment by JustOptimize** [comment]
Atm you can see the user specific permissions with this plugin
![image](https://user-images.githubusercontent.com/54294419/206475699-04f284a9-c295-4cae-a776-f0800c7e516c.png)

I will implement it in the hidden channel page further in the developement, thanks for the suggestion!

**Comment by HistoricTheater** [comment]
This addon should be about showing hidden channels and is feature creating horribly.

**Comment by JustOptimize** [comment]
> This addon should be about showing hidden channels and is feature creeping horribly.

Hi, I can't understand what you've written. Please try using a different translator like [deepl](https://www.deepl.com/translator)

**Comment by HistoricTheater** [comment]
> Hi, I can't understand what you've written. Please try using a different translator like [deepl](https://www.deepl.com/translator)

There is nothing to translate, this addon shouldnt have all these extra "features" in it when it has a singular purpose, to show hidden channels. All these other recently added permission types and features are out of scope of doing as what the addon is called, "Show Hidden Channels".

**Comment by JustOptimize** [comment]
Something that cannot be added by other plugins by whom else should it be implemented?
(This issue is about a feature on the hidden channels page.)

If these extra features upset you you could ask for a lite version of this plugin or request an extra setting to disable it by opening an issue

**Comment by JustOptimize** [comment]
@CandleMoth, if you want to, you can try this feature already by downloading [this](https://github.com/JustOptimize/return-ShowHiddenChannels/blob/dev-unstable/ShowHiddenChannels.plugin.js).
The UI it's bit rough but it does it's job.
I would be grateful if you could give me some feedback 😉

**Comment by JustOptimize** [comment]
> If these extra features upset you you could ask for a lite version of this plugin or request an extra setting to disable it by opening an issue

I added a setting because I don't like it either.

**Comment by JustOptimize** [comment]
> The UI it's bit rough but it does it's job.

![image](https://user-images.githubusercontent.com/54294419/207169250-384ce3d0-5cf7-43c5-9269-8e7518874ed9.png)

Now it's nice
