### ISSUE TITLE
(Bug) Servers that use the "Channels & Roles" feature do not show any hidden channels.

### ISSUE THREAD

**Issue by MrTente** [JustOptimize/return-ShowHiddenChannels#89]

**Comment by JustOptimize** [comment]
Can you send me an invite for a server that use it? thanks <3

**Comment by MrTente** [comment]
Well hidden channels have seemingly started popping up in channels that use the feature now, I don't know what the problem was but anyway.

 if you still want a link to a server that uses the feature: https://discord.gg/discord-townhall

**Comment by JustOptimize** [comment]
> if you still want a link to a server that uses the feature: https://discord.gg/discord-townhall

I can't get into that server 😠, I already tried to get into it a year ago or so and failed trying for a week, and now I still can't even though I've been trying for a few days already



> Well hidden channels have seemingly started popping up in channels that use the feature now, I don't know what the problem was but anyway.

Great! If you encounter other problems, feel free to open another issue 😉
