### ISSUE TITLE
Hidden channels showing unread

### ISSUE THREAD

**Issue by darkarrow** [JustOptimize/return-ShowHiddenChannels#9]
When in a server with hidden channels it will show the indicator that there are unread channels either up or down, where ever the channel is, even if it is a channel that is hidden. The guild doesn't show unread if I switch which guild I have in focus and the channel doesn't look unread just looks like a hidden channel but after scrolling so the channel is off screen the unread notification comes up.

Also thank you for continuing this plugin after it was removed by the original author.

**Comment by JustOptimize** [comment]
Idk why but I can't replicate this bug.
As a temporary fix you could try muting the server/channel

**Comment by JustOptimize** [comment]
Can anyone replicate this bug or is he just using Tharki-God's plugin? (known for having this issue)

**Comment by DTraitor** [comment]
I had this issue before the plugin was discontinued, installing this one right now

**Comment by Nexinity7** [comment]
Having this issue as well, but it doesnt mark the server as having a notification, only an new unreads marker when scrolling through channels

**Comment by Schlock-Konn** [comment]
I am experiencing this bug as well

**Comment by JustOptimize** [comment]
Can anyone confirm that the patch works?

**Comment by DTraitor** [comment]
> Can anyone confirm that the patch works?

Yep, everything works just fine now

**Comment by Nexinity7** [comment]
Seems to be working!
