### ISSUE TITLE
Revert "Removed MarkUnread option since it was kinda useless"

### ISSUE THREAD

**Issue by DPTJKKVH** [JustOptimize/return-ShowHiddenChannels#90]
I want to request that this feature is reinstated since it is not useless at all. Allowing hidden channels to show as unread is necessary for two important uses cases:

**1. Seeing if a certain channel had recent activity.**
Knowing that something has been written in a particular channel can be VERY important information even without knowing what has been written. By automatically showing all hidden channels as read this use case gets lost entirely.

**2. Highlighting if and when a new hidden channel gets created.**
I mute the hidden channels I don't care for so I can immediately see when a new one pops up by having the channel show as unread.

**Comment by JustOptimize** [comment]
Oh, sure, thanks for the suggestion!

**Comment by DPTJKKVH** [comment]
Thanks! Much appreciated! Not just for that but for reviving and maintaining this plugin in general.
