### ISSUE TITLE
(Bug) Right Clicking SERVER Crash

### ISSUE THREAD

**Issue by ZorkIsEmo** [JustOptimize/return-ShowHiddenChannels#91]
Right clicking any channels crashes better discord for me

**Comment by 9gga** [comment]
I dont think that this plugin is causing that. I believe that it is the Permissionviewer plugin by zerebos that does it.

**Comment by Nasur-m8** [comment]
> Go to betterdiscord official discord channel under known-issues and you will find a quickfix

There is sadly nothing there about a quick-fix

**Comment by JustOptimize** [comment]
![SmartSelect_20221213-085419.jpg](https://user-images.githubusercontent.com/54294419/207257939-ce9fc6a7-8b8d-481d-9f88-542b5ecc4391.jpg)

(It's in the support forum)

**Comment by 9gga** [comment]
Betterdiscord pushed an update that sorts this out.

**Comment by JustOptimize** [comment]
> Betterdiscord pushed an update that sorts this out.

This issue was fixed yesterday with this patch: [18401a0](https://github.com/JustOptimize/return-ShowHiddenChannels/commit/18401a0d92e5eb458ac51f995f0d4ecbc8a8e06b), gonna undo it in a few days while I wait people to update betterdiscord 

PS: keep this issue open so I don't forget to do it
