### ISSUE TITLE
[Bug] Inaccurate roles for "Roles that can see this channel"

### ISSUE THREAD

**Issue by J-URL** [JustOptimize/return-ShowHiddenChannels#92]
Channels that give roles permissions (such as Send Messages) but also have it set so that role cannot see the channel still show up under "Roles that can see this channel"

**Comment by JustOptimize** [comment]
OH, will fix it soon! :), thanks

**Comment by JustOptimize** [comment]
![image](https://user-images.githubusercontent.com/54294419/207988488-657d9813-91e8-4add-a388-64e39aa4591b.png)

😉
